import { Modal, Notice, type TFile } from "obsidian";
import { confirmDialog } from "../ui/confirm";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { parseActionList } from "../domain/action-import";
import { parseSubprojectList } from "../domain/project-import";
import { ancestorsToActivate } from "../domain/project-tree";
import { parseProjectTags, planProjectParentChange, projectTagAdditions } from "../domain/project-board";
import type { Action, ActionInput, Project, ProjectChanges } from "../domain/types";
import { confirmCompleteProject } from "../ui/complete-project";
import { confirmDeleteProject } from "../ui/delete-project";
import { activationOptions } from "../ui/project-moves";
import { isVaultImage, resolveVaultImage } from "../ui/image-input";
import type { GtdServices } from "../ui/services";
import { normalizeVaultPath } from "../utils/path";
import { localDate, parseDateOnly } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import {
  elmSnapshot,
  parseModalCommand,
  type ElmActionChanges,
  type ElmImportedRow,
  type ElmNewActionInput,
  type ElmModalCommand,
  type ElmModalEvent,
  type ElmScheduleInput,
} from "./protocol";

/** Which form the Elm modal program should open with. */
export type ElmModalForm =
  | { kind: "prompt"; title: string; placeholder: string }
  | { kind: "capture" }
  | { kind: "new-action"; projectId?: string; title?: string }
  | { kind: "edit-action"; actionId: string; allowProjectConversion: boolean; status?: Action["status"] }
  | { kind: "schedule-action"; actionId: string }
  | { kind: "import-actions"; projectId?: string }
  | { kind: "import-subprojects"; parentProjectId?: string }
  | { kind: "new-project"; parentProjectId?: string; status?: Project["status"]; title?: string }
  | { kind: "edit-project"; projectId: string }
  | { kind: "batch-tags"; projectIds: string[] }
  | { kind: "batch-parent"; projectIds: string[] }
  | { kind: "dependencies"; projectId: string };

interface ElmModalHandlers {
  /** Receives the value a prompt form submitted. */
  onPrompt?: (value: string) => void;
  /** Receives the file a new Project created. */
  onProjectCreated?: (file: TFile) => Promise<void>;
  /** Runs once a new Action was created. */
  onActionCreated?: () => Promise<void>;
  /** Runs once the modal has closed, however it closed, so a caller waiting on it is released. */
  onDismissed?: () => void;
}

interface ElmApp {
  ports: {
    modalsToHost: ElmOutgoingPort;
    modalsFromHost: { send(value: ElmModalEvent): void };
  };
}

/**
 * An Obsidian modal whose contents are the Elm `Modals` program.
 *
 * Obsidian keeps what it owns — the overlay, Escape, and focus trapping — and
 * Elm owns the form inside it.
 */
export class ElmModal extends Modal {
  private app_: ElmApp | null = null;
  private closed = false;
  private unsubscribePort: (() => void) | null = null;

  constructor(
    private readonly services: GtdServices,
    private readonly form: ElmModalForm,
    private readonly handlers: ElmModalHandlers = {},
  ) {
    super(services.app);
  }

  onOpen(): void {
    this.closed = false;
    this.modalEl.addClass("dg-modal-shell");
    this.contentEl.addClass("dg-modal");
    const module = Elm.Modals;
    if (!module) throw new Error("The Elm Modals module was not compiled.");
    this.app_ = module.init({
      node: this.contentEl.createDiv(),
      flags: {
        snapshot: elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate()),
        // Only the Project forms pick an image; listing them costs a walk over the whole vault.
        images: this.form.kind === "new-project" || this.form.kind === "edit-project" ? this.vaultImages() : [],
        form: this.form,
      },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app_.ports.modalsToHost,
      parse: parseModalCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      surface: "Dialog",
      failureMessage: "The GTD operation failed.",
      notifyErrors: false,
    });
  }

  onClose(): void {
    this.closed = true;
    this.unsubscribePort?.();
    this.unsubscribePort = null;
    this.app_ = null;
    this.contentEl.empty();
    this.handlers.onDismissed?.();
  }

  private vaultImages(): string[] {
    return this.services.app.vault
      .getFiles()
      .filter(isVaultImage)
      .map((file) => file.path)
      .sort((left, right) => left.localeCompare(right));
  }

  private send(event: ElmModalEvent): void {
    if (!this.closed) this.app_?.ports.modalsFromHost.send(event);
  }

  private async execute(command: ElmModalCommand): Promise<unknown> {
    switch (command.type) {
      case "close-modal":
        this.close();
        return;
      case "submit-prompt":
        this.handlers.onPrompt?.(command.value);
        return;
      case "capture-inbox-item":
        await this.services.repository.createInboxItem(command.title);
        new Notice("Captured to Inbox.");
        return;
      case "save-new-action":
        // One file written straight into the Actions folder: going through an Inbox Item
        // first cost four writes, and every open view redrew after each of them.
        await this.services.repository.createAction(actionInput(command.input));
        await this.handlers.onActionCreated?.();
        new Notice("Action created.");
        return;
      case "save-action":
        await this.services.repository.updateAction(command.actionId, actionChanges(command.changes));
        return;
      case "schedule-action":
        await this.services.repository.updateAction(command.actionId, {
          status: "scheduled",
          ...scheduleChanges(command.schedule),
        });
        return;
      case "convert-action-to-subproject":
        return this.convertToSubproject(command.actionId, command.title, command.parentProjectId);
      case "save-new-project": {
        const image = this.validatedImage(command.input.image, "");
        const file = await this.services.repository.createProject({
          title: command.input.title,
          status: command.input.status,
          ...(command.input.area ? { area: command.input.area } : {}),
          ...(image ? { image } : {}),
          ...(command.input.tags.length ? { tags: parseProjectTags(command.input.tags.join(",")) } : {}),
          ...(command.input.parentProjectId ? { parentProjectId: command.input.parentProjectId } : {}),
        });
        await this.handlers.onProjectCreated?.(file);
        return;
      }
      case "save-project": {
        const current = this.services.repository.index.getSnapshot().projectsById.get(command.projectId);
        const sourcePath = current?.file.path ?? "";
        // Declining the completion prompt still saves the other edits.
        let status = command.changes.status === "completed" && !await confirmCompleteProject(this.services, command.projectId)
          ? current?.status ?? command.changes.status
          : command.changes.status;
        let parentProjectId = command.changes.parentProjectId;
        // An Active Project activates the Projects above it; declining to reopen a
        // finished one keeps the old status and parent, and still saves the rest.
        let options = await activationOptions(this.services, current, status, parentProjectId || undefined);
        if (!options) {
          status = current?.status ?? status;
          parentProjectId = current?.parentProjectId ?? "";
          options = {};
        }
        const activating = status === "active"
          ? ancestorsToActivate(parentProjectId || undefined, this.services.repository.index.getSnapshot().projectsById)
          : [];
        await this.services.repository.updateProject(command.projectId, {
          title: command.changes.title,
          status,
          activateAt: command.changes.activateAt,
          area: command.changes.area,
          image: this.validatedImage(command.changes.image, sourcePath),
          tags: parseProjectTags(command.changes.tags.join(",")),
          reviewed: command.changes.reviewed,
          parentProjectId,
        }, options);
        if (activating.length) new Notice(`Also activated ${activating.map((item) => `“${item.title}”`).join(", ")}.`);
        return;
      }
      case "trash-project":
        return confirmDeleteProject(this.services, command.projectId);
      case "set-project-blockers":
        await this.services.repository.updateProject(command.projectId, {
          blockedByProjectIds: command.blockedByProjectIds,
        });
        return;
      case "add-project-tags":
        return this.addTags(command.projectIds, command.tags);
      case "set-projects-parent":
        return this.setParent(command.projectIds, command.parentProjectId);
      case "parse-import-list":
        return command.kind === "actions" ? importedActions(command.text) : importedSubprojects(command.text);
      case "import-action-list": {
        const parsed = parseActionList(command.text);
        const created = await this.services.repository.importActions(parsed.map((action) => ({
          title: action.title,
          status: action.done ? "done" as const : "next" as const,
          context: action.contexts[0] ?? "",
          ...(command.projectId ? { projectId: command.projectId } : {}),
        })));
        new Notice(`Imported ${created} Action${created === 1 ? "" : "s"}.`);
        return;
      }
      case "import-subproject-list": {
        const parsed = parseSubprojectList(command.text);
        const created = await this.services.repository.importSubprojects(
          command.parentProjectId,
          parsed.map((project) => ({
            title: project.title,
            status: project.done ? "completed" as const : "active" as const,
            tags: project.tags,
          })),
        );
        new Notice(`Imported ${created} Sub-project${created === 1 ? "" : "s"}.`);
        return;
      }
    }
    return assertNever(command);
  }

  private async convertToSubproject(actionId: string, title: string, parentProjectId: string): Promise<boolean> {
    const snapshot = this.services.repository.index.getSnapshot();
    const action = snapshot.actionsById.get(actionId);
    if (!action) throw new Error("This Action no longer exists.");
    const parent = snapshot.projectsById.get(parentProjectId);
    if (!parent) throw new Error("The selected parent Project no longer exists.");
    if (!await confirmDialog(this.services.app, {
      title: `Convert “${action.title}” to a sub-project?`,
      message: `It becomes an Active sub-project of “${parent.title}”. The Action body is copied to Project Notes, then the original Action is moved to Obsidian's trash.`,
      confirmText: "Convert",
    })) return false;
    await this.services.repository.convertActionToSubproject(action.id, title, parent.id);
    new Notice(`Converted “${action.title}” to a sub-project.`);
    return true;
  }

  /** Keeps Obsidian's link-resolution behavior for typed image paths. */
  private validatedImage(rawPath: string, sourcePath: string): string {
    const path = normalizeVaultPath(rawPath);
    if (path && !resolveVaultImage(this.services.app, path, sourcePath)) {
      throw new Error("Select an image file from the vault.");
    }
    return path;
  }

  /** Adds tags to every selected Project that is missing one, keeping what they carry. */
  private async addTags(projectIds: readonly string[], rawTags: readonly string[]): Promise<void> {
    const tags = parseProjectTags(rawTags.join(","));
    if (!tags.length) throw new Error("Name at least one tag.");
    const snapshot = this.services.repository.index.getSnapshot();
    const projects = projectIds
      .map((id) => snapshot.projectsById.get(id))
      .filter((project): project is Project => Boolean(project));
    const { updates, unchanged } = projectTagAdditions(projects, tags);
    if (!updates.size) {
      throw new Error(unchanged.length
        ? `Every selected Project already has ${tags.length === 1 ? "that tag" : "those tags"}.`
        : "These Projects no longer exist.");
    }

    const result = await this.applyProjectChanges([...updates].map(([id, next]) => [id, { tags: next }] as const));
    if (!result.applied && result.failure) throw new Error(result.failure);
    new Notice([
      `Tagged ${projectCount(result.applied)}`,
      unchanged.length ? `${unchanged.length} already tagged` : "",
      result.failure ? `${updates.size - result.applied} failed — ${result.failure}` : "",
    ].filter(Boolean).join(" · "));
  }

  /** Re-parents every selected Project the move would actually change. */
  private async setParent(projectIds: readonly string[], parentProjectId: string): Promise<void> {
    const snapshot = this.services.repository.index.getSnapshot();
    const plan = planProjectParentChange(projectIds, parentProjectId, snapshot.projectsById);
    if (!plan.changing.length) {
      throw new Error(plan.blocked.length
        ? "That parent would create a hierarchy cycle."
        : plan.unchanged.length ? "The selected Projects already have that parent." : "These Projects no longer exist.");
    }
    const parentTitle = parentProjectId ? snapshot.projectsById.get(parentProjectId)?.title ?? "" : "";
    const result = await this.applyProjectChanges(plan.changing.map((id) => [id, { parentProjectId }] as const));
    if (!result.applied && result.failure) throw new Error(result.failure);
    new Notice([
      parentTitle
        ? `Moved ${projectCount(result.applied)} under “${parentTitle}”`
        : `Moved ${projectCount(result.applied)} to the top level`,
      plan.blocked.length ? `${plan.blocked.length} would cycle` : "",
      result.failure ? `${plan.changing.length - result.applied} failed — ${result.failure}` : "",
    ].filter(Boolean).join(" · "));
  }

  /** Applies Project edits one file at a time so a single failure cannot abandon the rest. */
  private async applyProjectChanges(
    changes: readonly (readonly [string, ProjectChanges])[],
  ): Promise<{ applied: number; failure: string | undefined }> {
    let applied = 0;
    let failure: string | undefined;
    for (const [id, change] of changes) {
      try {
        await this.services.repository.updateProject(id, change);
        applied += 1;
      } catch (error) {
        failure ??= error instanceof Error ? error.message : "The Project could not be updated.";
      }
    }
    return { applied, failure };
  }
}

function projectCount(count: number): string {
  return `${count} Project${count === 1 ? "" : "s"}`;
}

function importedActions(text: string): ElmImportedRow[] {
  return parseActionList(text).map((action) => ({
    title: action.title,
    tags: action.contexts,
    done: action.done,
  }));
}

function importedSubprojects(text: string): ElmImportedRow[] {
  return parseSubprojectList(text).map((project) => ({
    title: project.title,
    tags: project.tags,
    done: project.done,
  }));
}

function actionInput(input: ElmNewActionInput): ActionInput {
  return {
    title: input.title,
    status: input.status,
    ...(input.projectId ? { projectId: input.projectId } : {}),
    context: input.context,
    ...(input.waitingSince ? { waitingSince: input.waitingSince } : {}),
    ...(input.followUp ? { followUp: input.followUp } : {}),
    ...scheduleChanges(input.schedule),
  };
}

function actionChanges(changes: ElmActionChanges) {
  return {
    title: changes.title,
    status: changes.status,
    projectId: changes.projectId,
    context: changes.context,
    energy: changes.energy,
    due: changes.due,
    followUp: changes.followUp,
    ...(changes.waitingSince ? { waitingSince: changes.waitingSince } : {}),
    ...scheduleChanges(changes.schedule),
  };
}

/**
 * Turns the schedule an editor stated into the absolute form a file stores.
 * Only the host knows the local zone, so this is the one conversion Elm defers.
 */
function scheduleChanges(schedule?: ElmScheduleInput): Pick<Action, "scheduledStart" | "durationMinutes"> | {} {
  if (!schedule) return {};
  if (schedule.kind === "all-day") {
    if (!parseDateOnly(schedule.date)) throw new Error("Choose a valid date.");
    return { scheduledStart: schedule.date };
  }
  const start = new Date(schedule.localStart);
  if (Number.isNaN(start.getTime()) || dateTimeLocalValue(start) !== schedule.localStart.slice(0, 16)) {
    throw new Error("Choose a valid date and time.");
  }
  return { scheduledStart: start.toISOString(), durationMinutes: schedule.durationMinutes };
}

function dateTimeLocalValue(date: Date): string {
  const pad = (part: number) => String(part).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}
