import { Notice } from "obsidian";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import { elmSnapshot, parseBrainstormCommand, type ElmBrainstormCommand, type ElmBrainstormEvent } from "./protocol";

const WORDS = [
  "alignment", "ambiguity", "attention", "boundary", "breakthrough", "calm", "challenge", "clarity", "coherence", "constraint",
  "contrast", "curiosity", "decision", "empathy", "friction", "generosity", "momentum", "possibility", "question", "simplicity",
  "absorb", "accelerate", "adapt", "align", "amplify", "anchor", "assemble", "balance", "blend", "branch",
  "bridge", "build", "calibrate", "capture", "carve", "cascade", "clarify", "combine", "compress", "connect",
  "algae", "aquifer", "archipelago", "aurora", "avalanche", "bark", "basalt", "blossom", "boulder", "canopy",
  "canyon", "cave", "cedar", "current", "delta", "forest", "glacier", "horizon", "island", "river",
  "anchor", "antenna", "anvil", "arcade", "arrow", "atrium", "axle", "balcony", "beacon", "bellows",
  "blade", "bridge", "compass", "hinge", "key", "lens", "mirror", "pulley", "sieve", "window",
  "airy", "amber", "aromatic", "azure", "bitter", "blurred", "bold", "braided", "brittle", "briny",
  "crisp", "dappled", "echoing", "glowing", "grainy", "luminous", "muted", "rough", "silken", "warm",
];

interface ElmApp {
  ports: {
    brainstormToHost: ElmOutgoingPort;
    brainstormFromHost: { send(value: ElmBrainstormEvent): void };
  };
}

export class ElmBrainstormHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(private readonly node: HTMLElement, private readonly services: GtdServices) {
    const module = Elm.Brainstorm;
    if (!module) throw new Error("The Elm Brainstorm module was not compiled.");
    this.app = module.init({
      node: this.node,
      flags: {
        snapshot: this.snapshot(),
        words: pickRandom(WORDS, 10),
        randomIndex: Math.floor(Math.random() * 1_000_000),
      },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.brainstormToHost,
      parse: parseBrainstormCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      failureMessage: "Could not save the brainstorm.",
    });
    this.unsubscribe = services.repository.index.subscribe(() => this.refresh());
  }

  refresh(): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private send(event: ElmBrainstormEvent): void {
    if (!this.closed) this.app.ports.brainstormFromHost.send(event);
  }

  private async execute(command: ElmBrainstormCommand): Promise<unknown> {
    switch (command.type) {
      case "load-brainstorm-outcome": {
        const project = this.services.repository.index.getSnapshot().projectsById.get(command.projectId);
        if (!project) throw new Error("This Project no longer exists.");
        const desiredOutcome = await this.services.repository.readDesiredOutcome(project);
        this.send({ type: "brainstorm-outcome", projectId: project.id, desiredOutcome });
        return;
      }
      case "save-brainstorm":
        await this.services.repository.saveBrainstorm(command.actionId, command.ideas, command.desiredOutcome);
        new Notice(command.desiredOutcome === undefined
          ? "Brainstorm captured to Inbox; Action completed."
          : "Brainstorm saved to Project support material; Action completed.");
        return;
      case "save-standalone-brainstorm":
        await this.services.repository.saveStandaloneBrainstorm(command.topic, command.ideas);
        new Notice("Standalone brainstorm captured to Inbox.");
        return;
      case "shuffle-brainstorm-words":
        return pickRandom(WORDS, 10);
      case "focus-brainstorm-ideas": {
        const textarea = this.node.querySelector<HTMLTextAreaElement>("textarea[data-brainstorm-ideas]");
        window.requestAnimationFrame(() => {
          textarea?.focus();
          textarea?.setSelectionRange(command.start, command.end);
        });
        return;
      }
      case "show-project":
        this.services.showProjectDetail(command.projectId);
        return;
    }
    return assertNever(command);
  }
}

function pickRandom<T>(items: readonly T[], count: number): T[] {
  const pool = [...items];
  const result: T[] = [];
  while (pool.length && result.length < count) result.push(...pool.splice(Math.floor(Math.random() * pool.length), 1));
  return result;
}
