import { Notice } from "obsidian";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { findSource, type FeedItem } from "../domain/feed";
import { feedItemNote, feedItemTitle } from "../domain/feed-triage";
import type { FeedService } from "../feeds/feed-service";
import type { GtdServices } from "../ui/services";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import { elmFeeds, parseFeedsCommand, type ElmFeedsCommand, type ElmFeedsEvent } from "./protocol";

interface ElmApp {
  ports: {
    feedsToHost: ElmOutgoingPort;
    feedsFromHost: { send(value: ElmFeedsEvent): void };
  };
}

export class ElmFeedsHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(node: HTMLElement, private readonly services: GtdServices, private readonly feeds: FeedService) {
    const module = Elm.Feeds;
    if (!module) throw new Error("The Elm Feeds module was not compiled.");
    this.app = module.init({ node, flags: { feeds: this.payload() } }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.feedsToHost,
      parse: parseFeedsCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      failureMessage: "The Feeds operation failed.",
    });
    this.unsubscribe = feeds.subscribe(() => this.send({ type: "feeds", feeds: this.payload() }));
    // Opening the view before the plugin finished starting should still show the store.
    void feeds.load();
  }

  refresh(): void {
    this.send({ type: "feeds", feeds: this.payload() });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  private payload() {
    const status = this.feeds.getStatus();
    return elmFeeds(this.feeds.getStore(), status, {
      enabled: this.services.getSettings().feeds.enabled,
      undoCount: this.feeds.undoSize(),
    });
  }

  private send(event: ElmFeedsEvent): void {
    if (!this.closed) this.app.ports.feedsFromHost.send(event);
  }

  private async execute(command: ElmFeedsCommand): Promise<unknown> {
    switch (command.type) {
      case "refresh-feeds": {
        const result = await this.feeds.fetchAll();
        new Notice(result.added ? `Fetched ${result.added} new Feed Item${result.added === 1 ? "" : "s"}.` : "No new Feed Items.");
        return;
      }
      case "add-feed": {
        const url = await this.services.promptForText("Subscribe to a feed", "https://example.com/feed.xml");
        if (!url) return;
        const source = await this.feeds.addFeed(url);
        new Notice(`Subscribed to “${source.title}”.`);
        return;
      }
      case "keep-feed-items": {
        const kept = await this.keep(command.keys);
        new Notice(`Kept ${kept} Feed Item${kept === 1 ? "" : "s"} in the Inbox.`);
        return;
      }
      case "discard-feed-items": {
        const discarded = await this.feeds.discard(command.keys);
        // Discarding is state, not deletion, so the view's Undo is the whole recovery story.
        if (discarded) new Notice(`Discarded ${discarded} Feed Item${discarded === 1 ? "" : "s"}. Undo is in the header.`);
        return;
      }
      case "undo-feed-discard": {
        const restored = await this.feeds.undoLastSweep();
        if (restored) new Notice(`Put ${restored} Feed Item${restored === 1 ? "" : "s"} back.`);
        return;
      }
      case "open-link": {
        const url = new URL(command.url);
        if (url.protocol !== "http:" && url.protocol !== "https:") throw new Error("Only http and https links can be opened.");
        window.open(url.toString(), "_blank", "noopener,noreferrer");
        return;
      }
      case "open-inbox":
        this.services.openInbox();
        return;
    }
    return assertNever(command);
  }

  /**
   * Promotes Feed Items to Inbox Items.
   *
   * Items are written one at a time and only then resolved, so a failure part way
   * through leaves the rest of the sweep on the list rather than losing it.
   */
  private async keep(keys: readonly string[]): Promise<number> {
    const items = keys.map((key) => this.feeds.findItem(key)).filter((item): item is FeedItem => Boolean(item));
    const consumed: string[] = [];
    try {
      for (const item of items) {
        await this.createInboxItem(item);
        consumed.push(item.key);
      }
    } finally {
      if (consumed.length) await this.feeds.consume(consumed);
    }
    return consumed.length;
  }

  /** Returns the new Inbox Item's ID. */
  private async createInboxItem(item: FeedItem): Promise<string> {
    const feedTitle = findSource(this.feeds.getStore(), item.feedId)?.title ?? "";
    const created = await this.services.repository.createIdentifiedInboxItem(feedItemTitle(item), feedItemNote(item, feedTitle));
    return created.id;
  }
}
