// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { TFile } from "obsidian";
import { findRun } from "../domain/checklist";
import type { ChecklistService } from "../checklists/checklist-service";
import type { GtdServices } from "../ui/services";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import {
  elmChecklistRun,
  elmChecklists,
  parseChecklistsCommand,
  type ChecklistNoteContent,
  type ElmChecklistsCommand,
  type ElmChecklistsEvent,
} from "./protocol";

interface ElmApp {
  ports: {
    checklistsToHost: ElmOutgoingPort;
    checklistsFromHost: { send(value: ElmChecklistsEvent): void };
  };
}

/** Hosts the Checklists view. Runs live in `ChecklistService`; this view only shows one. */
export class ElmChecklistsHost {
  private app: ElmApp | null = null;
  private readonly unsubscribeChecklists: () => void;
  private unsubscribePort: () => void = () => undefined;
  /** The run the view shows, or `null` for the list of checklists. */
  private shownRunId: string | null;
  private version = 0;
  private closed = false;

  constructor(
    private readonly node: HTMLElement,
    private readonly services: GtdServices,
    private readonly checklists: ChecklistService,
    initialRunId: string | null,
  ) {
    this.shownRunId = initialRunId;
    this.unsubscribeChecklists = checklists.subscribe(() => void this.refresh());
    void this.mount();
  }

  async refresh(): Promise<void> {
    const version = ++this.version;
    const state = await this.state();
    if (version === this.version) this.send({ type: "checklists", checklists: state });
  }

  showRun(runId: string | null): void {
    this.shownRunId = runId;
    void this.refresh();
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribeChecklists();
  }

  private async mount(): Promise<void> {
    await this.checklists.load();
    const flags = await this.state();
    if (this.closed) return;
    const module = Elm.Checklists;
    if (!module) throw new Error("The Elm Checklists module was not compiled.");
    const app = module.init({ node: this.node, flags }) as ElmApp;
    this.app = app;
    this.unsubscribePort = subscribeElmCommands({
      port: app.ports.checklistsToHost,
      parse: parseChecklistsCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      failureMessage: "The checklist operation failed.",
    });
  }

  private async state() {
    const settings = this.services.getSettings().checklists;
    const store = this.checklists.getStore();
    const notes: ChecklistNoteContent[] = [];
    for (const note of this.checklists.checklists()) {
      notes.push({ ...note, blocks: (await this.checklists.read(note.path)) ?? [] });
    }
    const run = this.shownRunId ? findRun(store, this.shownRunId) : undefined;
    if (this.shownRunId && !run) this.shownRunId = null;
    const shown = run ? elmChecklistRun(run, notes.find((note) => note.path === run.path)?.blocks ?? await this.checklists.read(run.path), store) : null;
    return elmChecklists(notes, store, settings.daily, settings.directory, shown);
  }

  private send(event: ElmChecklistsEvent): void {
    if (!this.closed) this.app?.ports.checklistsFromHost.send(event);
  }

  private async execute(command: ElmChecklistsCommand): Promise<unknown> {
    switch (command.type) {
      case "start-checklist-run": {
        const run = await this.checklists.begin(command.path);
        this.showRun(run.id);
        return;
      }
      case "show-checklist-run":
        this.showRun(command.runId);
        return;
      case "mark-checklist-item":
        return this.checklists.mark(command.runId, command.key, command.state);
      case "finish-checklist-run":
        return this.checklists.finish(command.runId);
      case "discard-checklist-run":
        this.shownRunId = null;
        return this.checklists.discard(command.runId);
      case "capture-from-checklist":
        return captureFromChecklist(this.services, command.path, command.text);
      case "open-checklist-pomodoro":
        this.services.openChecklistPomodoro(command.path);
        return;
      case "open-file": {
        const file = this.services.app.vault.getAbstractFileByPath(command.path);
        if (!(file instanceof TFile)) throw new Error("This checklist no longer exists.");
        return this.services.openFile(file);
      }
    }
    return assertNever(command);
  }
}

/**
 * Captures what an item turned up as an Inbox Item: a checklist finds work, it doesn't
 * hold it. The Item links back to the checklist and quotes the item.
 */
export async function captureFromChecklist(services: GtdServices, path: string, item: string): Promise<void> {
  const title = await services.promptForText("Capture to Inbox", `What came up at “${plainText(item)}”?`);
  if (!title.trim()) return;
  const file = services.app.vault.getAbstractFileByPath(path);
  const link = file instanceof TFile ? services.app.fileManager.generateMarkdownLink(file, "") : `“${path}”`;
  await services.repository.createInboxItem(title.trim(), `From the checklist ${link}, at:\n\n> ${item}\n`);
}

/** An item's text without its link brackets, for a prompt. */
function plainText(markdown: string): string {
  return markdown.replace(/\[\[([^\]|]*\|)?([^\]]*)\]\]/g, "$2").replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
}
