import { Notice, Platform } from "obsidian";
import { askLocalPartner } from "../brainstorm/local-partner";
import { isVaultImage } from "../ui/image-input";
import { isPathInDirectory } from "../utils/path";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import { elmSnapshot, parseBrainstormCommand, type ElmBrainstormCommand, type ElmBrainstormEvent } from "./protocol";

const WORDS = [
  "alignment", "ambiguity", "attention", "boundary", "breakthrough", "calm", "challenge", "clarity", "coherence", "constraint",
  "contrast", "curiosity", "decision", "empathy", "friction", "generosity", "momentum", "possibility", "question", "simplicity",
  "absorb", "accelerate", "adapt", "align", "amplify", "anchor", "assemble", "balance", "blend", "branch",
  "bridge", "build", "calibrate", "capture", "carve", "cascade", "clarify", "combine", "compress", "connect",
  "algae", "aquifer", "archipelago", "aurora", "avalanche", "bark", "basalt", "blossom", "boulder", "canopy",
  "canyon", "cave", "cedar", "current", "delta", "forest", "glacier", "horizon", "island", "river",
  "anchor", "antenna", "anvil", "arcade", "arrow", "atrium", "axle", "balcony", "beacon", "bellows",
  "blade", "bridge", "compass", "hinge", "key", "lens", "mirror", "pulley", "sieve", "window",
  "airy", "amber", "aromatic", "azure", "bitter", "blurred", "bold", "braided", "brittle", "briny",
  "crisp", "dappled", "echoing", "glowing", "grainy", "luminous", "muted", "rough", "silken", "warm",
];

interface ElmApp {
  ports: {
    brainstormToHost: ElmOutgoingPort;
    brainstormFromHost: { send(value: ElmBrainstormEvent): void };
  };
}

export class ElmBrainstormHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(private readonly node: HTMLElement, private readonly services: GtdServices) {
    const module = Elm.Brainstorm;
    if (!module) throw new Error("The Elm Brainstorm module was not compiled.");
    this.app = module.init({
      node: this.node,
      flags: {
        snapshot: this.snapshot(),
        words: pickRandom(WORDS, 10),
        randomIndex: Math.floor(Math.random() * 1_000_000),
        // The partner is the local model on this Mac, which a phone can't reach.
        partner: Platform.isDesktopApp,
        inspirations: this.inspirations(),
      },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.brainstormToHost,
      parse: parseBrainstormCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      surface: "Brainstorm",
      failureMessage: "Could not save the brainstorm.",
      // The partner reports its own trouble in the view, without a notice every turn.
      notifyErrors: false,
    });
    this.unsubscribe = services.repository.index.subscribe(() => this.refresh(), "Brainstorm");
  }

  refresh(): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    // An image added to the folder turns up in the next pass, as any vault change does.
    this.send({ type: "inspirations", urls: this.inspirations() });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  /** The inspiration folder's images, in a stable order, as addresses the view can show. */
  private inspirations(): string[] {
    const folder = this.services.getSettings().brainstorm.imagesDirectory;
    return this.services.app.vault.getFiles()
      .filter((file) => isVaultImage(file) && isPathInDirectory(file.path, folder))
      .sort((left, right) => left.path.localeCompare(right.path))
      .map((file) => this.services.app.vault.getResourcePath(file));
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private send(event: ElmBrainstormEvent): void {
    if (!this.closed) this.app.ports.brainstormFromHost.send(event);
  }

  private async execute(command: ElmBrainstormCommand): Promise<unknown> {
    switch (command.type) {
      case "load-brainstorm-outcome": {
        const project = this.services.repository.index.getSnapshot().projectsById.get(command.projectId);
        if (!project) throw new Error("This Project no longer exists.");
        const desiredOutcome = await this.services.repository.readDesiredOutcome(project);
        this.send({ type: "brainstorm-outcome", projectId: project.id, desiredOutcome });
        return;
      }
      case "save-brainstorm":
        await this.services.repository.saveBrainstorm(command.actionId, command.ideas, command.desiredOutcome);
        new Notice(command.desiredOutcome === undefined
          ? "Brainstorm captured to Inbox; Action completed."
          : "Brainstorm saved to Project support material; Action completed.");
        return;
      case "save-standalone-brainstorm":
        await this.services.repository.saveStandaloneBrainstorm(command.topic, command.ideas);
        new Notice("Standalone brainstorm captured to Inbox.");
        return;
      case "shuffle-brainstorm-words":
        return pickRandom(WORDS, 10);
      case "focus-brainstorm-ideas": {
        const textarea = this.node.querySelector<HTMLTextAreaElement>("textarea[data-brainstorm-ideas]");
        window.requestAnimationFrame(() => {
          textarea?.focus();
          textarea?.setSelectionRange(command.start, command.end);
        });
        return;
      }
      case "show-project":
        this.services.showProjectDetail(command.projectId);
        return;
      case "suggest-brainstorm-ideas":
        return askLocalPartner(this.services.getSettings().agent, () => this.services.agent.localModelKey(), {
          topic: command.topic,
          desiredOutcome: command.desiredOutcome,
          ideas: command.ideas,
          offered: command.offered,
        });
    }
    return assertNever(command);
  }
}

function pickRandom<T>(items: readonly T[], count: number): T[] {
  const pool = [...items];
  const result: T[] = [];
  while (pool.length && result.length < count) result.push(...pool.splice(Math.floor(Math.random() * pool.length), 1));
  return result;
}
