import { Notice, TFile } from "obsidian";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import type { InboxItem } from "../domain/types";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import { elmSnapshot, parseInboxCommand, type ElmInboxCommand, type ElmInboxEvent } from "./protocol";

interface ElmApp {
  ports: {
    inboxToHost: ElmOutgoingPort;
    inboxFromHost: { send(value: ElmInboxEvent): void };
  };
}

export class ElmInboxHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(node: HTMLElement, private readonly services: GtdServices, initialProcessing: boolean) {
    const module = Elm.Inbox;
    if (!module) throw new Error("The Elm Inbox module was not compiled.");
    this.app = module.init({
      node,
      flags: { snapshot: this.snapshot(), initialProcessing },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.inboxToHost,
      parse: parseInboxCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      failureMessage: "The Inbox operation failed.",
    });
    this.unsubscribe = services.repository.index.subscribe(() => this.send({ type: "snapshot", snapshot: this.snapshot() }));
  }

  refresh(startProcessing = false): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    if (startProcessing) this.send({ type: "start-processing" });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  private snapshot() {
    return elmSnapshot(
      this.services.repository.index.getSnapshot(),
      this.services.getSettings(),
      localDate(),
      (file) => this.services.app.vault.getResourcePath(file),
    );
  }

  private send(event: ElmInboxEvent): void {
    if (!this.closed) this.app.ports.inboxFromHost.send(event);
  }

  private async execute(command: ElmInboxCommand): Promise<unknown> {
    switch (command.type) {
      case "quick-capture":
        this.services.quickCapture();
        return;
      case "open-file": {
        const file = this.services.app.vault.getAbstractFileByPath(command.path);
        if (!(file instanceof TFile)) throw new Error(`File '${command.path}' no longer exists.`);
        await this.services.openFile(file);
        return;
      }
      case "read-inbox-body":
        return this.services.repository.readInboxBody(this.item(command.itemId));
      case "trash-inbox-item": {
        const item = this.item(command.itemId);
        await this.services.repository.trashInboxItem(item);
        new Notice(`Deleted “${item.title}”.`);
        return;
      }
      case "process-inbox": {
        const item = this.item(command.itemId);
        if (command.operation === "someday") await this.services.repository.processInboxAsSomedayProject(item, command.input);
        else if (command.operation === "file") await this.services.repository.processInboxAsReference(item, command.input);
        else await this.services.repository.processInboxAsNextAction(item, command.input);
        new Notice(command.operation === "someday"
          ? "Filed as a Someday/Maybe Project."
          : command.operation === "file"
            ? command.input.projectId || command.input.projectTitle ? "Filed with Project." : "Filed as General Reference."
            : "Next Action created.");
        return;
      }
    }
    return assertNever(command);
  }

  private item(id: string): InboxItem {
    const item = this.services.repository.index.getSnapshot().inboxItems.find((candidate) => candidate.id === id);
    if (!item) throw new Error("This Inbox Item no longer exists.");
    return item;
  }
}
