import { Notice, TFile } from "obsidian";
import { trashWithUndo } from "../ui/undo";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import type { Action, InboxItem } from "../domain/types";
import type { GtdServices } from "../ui/services";
import { localDate, parseDateOnly } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import { elmSnapshot, parseInboxCommand, type ElmInboxCommand, type ElmInboxEvent, type ElmScheduleInput } from "./protocol";

interface ElmApp {
  ports: {
    inboxToHost: ElmOutgoingPort;
    inboxFromHost: { send(value: ElmInboxEvent): void };
  };
}

export class ElmInboxHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(node: HTMLElement, private readonly services: GtdServices, initialProcessing: boolean) {
    const module = Elm.Inbox;
    if (!module) throw new Error("The Elm Inbox module was not compiled.");
    this.app = module.init({
      node,
      flags: { snapshot: this.snapshot(), initialProcessing },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.inboxToHost,
      parse: parseInboxCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      failureMessage: "The Inbox operation failed.",
    });
    this.unsubscribe = services.repository.index.subscribe(() => this.send({ type: "snapshot", snapshot: this.snapshot() }));
  }

  refresh(startProcessing = false, itemId?: string): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    if (startProcessing) this.send({ type: "start-processing", ...(itemId ? { itemId } : {}) });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  private snapshot() {
    return elmSnapshot(
      this.services.repository.index.getSnapshot(),
      this.services.getSettings(),
      localDate(),
      (file) => this.services.app.vault.getResourcePath(file),
    );
  }

  private send(event: ElmInboxEvent): void {
    if (!this.closed) this.app.ports.inboxFromHost.send(event);
  }

  private async execute(command: ElmInboxCommand): Promise<unknown> {
    switch (command.type) {
      case "quick-capture":
        this.services.quickCapture();
        return;
      case "open-file": {
        const file = this.services.app.vault.getAbstractFileByPath(command.path);
        if (!(file instanceof TFile)) throw new Error(`File '${command.path}' no longer exists.`);
        await this.services.openFile(file);
        return;
      }
      case "read-inbox-body":
        return this.services.repository.readInboxBody(this.item(command.itemId));
      case "trash-inbox-item": {
        const item = this.item(command.itemId);
        await trashWithUndo(this.services.app, item.file, `Deleted “${item.title}”.`,
          () => this.services.repository.trashInboxItem(item));
        return;
      }
      case "process-inbox": {
        const item = this.item(command.itemId);
        const input = { ...command.input, ...scheduleChanges(command.input.schedule) };
        if (command.operation === "someday") await this.services.repository.processInboxAsSomedayProject(item, input);
        else if (command.operation === "file") await this.services.repository.processInboxAsReference(item, input);
        else await this.services.repository.processInboxAsNextAction(item, input);
        new Notice(command.operation === "someday"
          ? "Filed as a Someday/Maybe Project."
          : command.operation === "file"
            ? command.input.projectId || command.input.projectTitle ? "Filed with Project." : "Filed as General Reference."
            : `${actionLabel(command.input.status)} created.`);
        return;
      }
    }
    return assertNever(command);
  }

  private item(id: string): InboxItem {
    const item = this.services.repository.index.getSnapshot().inboxItems.find((candidate) => candidate.id === id);
    if (!item) throw new Error("This Inbox Item no longer exists.");
    return item;
  }
}

function actionLabel(status: Action["status"] | undefined): string {
  if (status === "waiting") return "Waiting Action";
  if (status === "scheduled") return "Scheduled Action";
  return "Next Action";
}

/** Turns an Elm editor's local schedule into the vault's absolute timestamp. */
function scheduleChanges(schedule?: ElmScheduleInput): Pick<Action, "scheduledStart" | "durationMinutes"> | {} {
  if (!schedule) return {};
  if (schedule.kind === "all-day") {
    if (!parseDateOnly(schedule.date)) throw new Error("Choose a valid scheduled date.");
    return { scheduledStart: schedule.date };
  }
  const start = new Date(schedule.localStart);
  if (Number.isNaN(start.getTime()) || dateTimeLocalValue(start) !== schedule.localStart.slice(0, 16)) {
    throw new Error("Choose a valid scheduled start time.");
  }
  return { scheduledStart: start.toISOString(), durationMinutes: schedule.durationMinutes };
}

function dateTimeLocalValue(date: Date): string {
  const pad = (part: number) => String(part).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}
