import { Notice, TFile } from "obsidian";
import { trashWithUndo } from "../ui/undo";
import { appleMailLink } from "../domain/mail-note";
import { findPullRequest, linksPullRequest, pullRequestLabel, reviewActionTitle } from "../domain/pull-request";
import { plainTitle } from "../domain/text";
import { projectsWithIssues } from "../domain/attention";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import type { Action, InboxItem } from "../domain/types";
import type { GtdServices } from "../ui/services";
import { localDate, parseDateOnly } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import { elmSnapshot, parseInboxCommand, type ElmInboxCommand, type ElmInboxEvent, type ElmScheduleInput } from "./protocol";

interface ElmApp {
  ports: {
    inboxToHost: ElmOutgoingPort;
    inboxFromHost: { send(value: ElmInboxEvent): void };
  };
}

export class ElmInboxHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(node: HTMLElement, private readonly services: GtdServices, initialProcessing: boolean) {
    const module = Elm.Inbox;
    if (!module) throw new Error("The Elm Inbox module was not compiled.");
    this.app = module.init({
      node,
      flags: { snapshot: this.snapshot(), initialProcessing, projectIssues: this.projectIssues() },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.inboxToHost,
      parse: parseInboxCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      surface: "Inbox",
      failureMessage: "The Inbox operation failed.",
    });
    this.unsubscribe = services.repository.index.subscribe(() => {
      this.send({ type: "snapshot", snapshot: this.snapshot() });
      this.send({ type: "project-issues", count: this.projectIssues() });
    }, "Inbox");
  }

  refresh(startProcessing = false, itemId?: string): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    this.send({ type: "project-issues", count: this.projectIssues() });
    if (startProcessing) this.send({ type: "start-processing", ...(itemId ? { itemId } : {}) });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  private snapshot() {
    return elmSnapshot(
      this.services.repository.index.getSnapshot(),
      this.services.getSettings(),
      localDate(),
      (file) => this.services.app.vault.getResourcePath(file),
    );
  }

  private send(event: ElmInboxEvent): void {
    if (!this.closed) this.app.ports.inboxFromHost.send(event);
  }

  private async execute(command: ElmInboxCommand): Promise<unknown> {
    switch (command.type) {
      case "quick-capture":
        this.services.quickCapture();
        return;
      case "open-file": {
        const file = this.services.app.vault.getAbstractFileByPath(command.path);
        if (!(file instanceof TFile)) throw new Error(`File '${command.path}' no longer exists.`);
        await this.services.openFile(file);
        return;
      }
      case "read-inbox-body": {
        // The pull request it links, if any, names the processor's + Review button.
        const text = await this.services.repository.readInboxBody(this.item(command.itemId));
        const pr = findPullRequest(text);
        return { text, pullRequest: pr ? pullRequestLabel(pr) : null };
      }
      case "show-project-issues":
        this.services.showProjectIssues();
        return;
      case "review-pull-request":
        return this.reviewPullRequest(this.item(command.itemId));
      case "read-desired-outcome": {
        const project = this.services.repository.index.getSnapshot().projectsById.get(command.projectId);
        if (!project) throw new Error("This Project no longer exists.");
        return this.services.repository.readDesiredOutcome(project);
      }
      case "trash-inbox-item": {
        const item = this.item(command.itemId);
        await trashWithUndo(this.services.app, item.file, `Deleted “${item.title}”.`,
          () => this.services.repository.trashInboxItem(item));
        return;
      }
      case "open-mail": {
        const link = appleMailLink(this.item(command.itemId).messageId ?? "");
        if (!link) throw new Error("This Inbox Item was not imported from email.");
        // Obsidian hands a `message:` link to macOS, which opens it in Apple Mail.
        window.open(link);
        return;
      }
      case "process-inbox": {
        const item = this.item(command.itemId);
        const input = { ...command.input, ...scheduleChanges(command.input.schedule) };
        if (command.operation === "someday" || command.operation === "backlog") {
          await this.services.repository.processInboxAsParkedProject(item, input, command.operation);
        } else if (command.operation === "file") await this.services.repository.processInboxAsReference(item, input);
        else await this.services.repository.processInboxAsNextAction(item, input);
        new Notice(command.operation === "someday"
          ? "Filed as a Someday/Maybe Project."
          : command.operation === "backlog"
            ? "Filed as a Backlog Project."
            : command.operation === "file"
            ? command.input.projectId || command.input.projectTitle ? "Filed with Project." : "Filed as General Reference."
            : `${actionLabel(command.input.status)} created.`);
        return;
      }
    }
    return assertNever(command);
  }

  /**
   * Turns an Item that links a GitHub pull request into a Next Action to review it, then
   * deletes the Item with Undo, as Delete & Next does. GitHub sends an email for every
   * request, comment and push, so when an open Action already links the pull request no
   * second one is made: the email only goes.
   */
  private async reviewPullRequest(item: InboxItem): Promise<void> {
    const repository = this.services.repository;
    const pr = findPullRequest(await repository.readInboxBody(item));
    if (!pr) throw new Error("This Inbox Item doesn't link a GitHub pull request.");
    const existing = repository.index.getSnapshot().actions
      .find((action) => action.status !== "done" && action.status !== "cancelled" && linksPullRequest(action.title, pr));
    let message: string;
    if (existing) {
      message = `“${plainTitle(existing.title)}” is already on your list; deleted “${item.title}”.`;
    } else {
      const title = reviewActionTitle(pr, item.title);
      const context = this.services.getSettings().mail.reviewContext.trim() || "Laptop";
      await repository.createAction({ title, status: "next", context });
      message = `Added the Next Action “${plainTitle(title)}” (@${context}) and deleted “${item.title}”.`;
    }
    // Undo brings the Item back; a review Action just made stays.
    await trashWithUndo(this.services.app, item.file, message, () => repository.trashInboxItem(item));
  }

  /** Projects with an issue: Inbox zero waits for them, since a stuck Project is a loose end too. */
  private projectIssues(): number {
    return projectsWithIssues(this.services.repository.index.getSnapshot());
  }

  private item(id: string): InboxItem {
    const item = this.services.repository.index.getSnapshot().inboxItems.find((candidate) => candidate.id === id);
    if (!item) throw new Error("This Inbox Item no longer exists.");
    return item;
  }
}

function actionLabel(status: Action["status"] | undefined): string {
  if (status === "waiting") return "Waiting Action";
  if (status === "scheduled") return "Calendar Action";
  return "Next Action";
}

/** Turns an Elm editor's local schedule into the vault's absolute timestamp. */
function scheduleChanges(schedule?: ElmScheduleInput): Pick<Action, "scheduledStart" | "durationMinutes"> | {} {
  if (!schedule) return {};
  if (schedule.kind === "all-day") {
    if (!parseDateOnly(schedule.date)) throw new Error("Choose a valid date.");
    return { scheduledStart: schedule.date };
  }
  const start = new Date(schedule.localStart);
  if (Number.isNaN(start.getTime()) || dateTimeLocalValue(start) !== schedule.localStart.slice(0, 16)) {
    throw new Error("Choose a valid date and time.");
  }
  return { scheduledStart: start.toISOString(), durationMinutes: schedule.durationMinutes };
}

function dateTimeLocalValue(date: Date): string {
  const pad = (part: number) => String(part).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}
