import { Menu, Notice } from "obsidian";
import { trashWithUndo } from "../ui/undo";
import { openWebLink } from "../ui/open-link";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { activeDescendantCounts, projectBreadcrumbs } from "../domain/project-hierarchy";
import { activeProjectBlockers, projectActionIssue } from "../domain/project-board";
import type { Project } from "../domain/types";
import { moveProject, setProjectStatus } from "../ui/project-moves";
import { confirmDeleteProject, confirmDeleteProjects } from "../ui/delete-project";
import { resolveVaultImage } from "../ui/image-input";
import { ElmModal } from "./elm-modals";
import { executeSupportCommand, projectDetail } from "./project-detail";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import {
  elmSnapshot,
  parseProjectsCommand,
  type ElmProjectsCommand,
  type ElmProjectsEvent,
  type ElmProjectsMenuEntry,
  type ElmProjectMetaDto,
} from "./protocol";

interface ElmApp {
  ports: {
    projectsToHost: ElmOutgoingPort;
    projectsFromHost: { send(value: ElmProjectsEvent): void };
  };
}

interface ProjectFlags {
  snapshot: ReturnType<typeof elmSnapshot>;
  projectMeta: ElmProjectMetaDto[];
  initialProjectId: string | null;
  isMac: boolean;
}

export class ElmProjectsHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribeAgent: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(
    node: HTMLElement,
    private readonly services: GtdServices,
    initialProjectId: string | null,
    private readonly onProjectChange: (projectId: string | null) => void,
  ) {
    const module = Elm.Projects;
    if (!module) throw new Error("The Elm Projects module was not compiled.");
    this.app = module.init({ node, flags: this.flags(initialProjectId) }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.projectsToHost,
      parse: parseProjectsCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      surface: "Projects",
      failureMessage: "The Project operation failed.",
    });
    this.unsubscribe = services.repository.index.subscribe(() => this.sendSnapshot(), "Projects");
    this.unsubscribeAgent = services.agent.subscribe(() => this.sendAgent());
    this.sendAgent();
  }

  refresh(): void {
    this.sendSnapshot();
  }

  showProject(projectId: string): void {
    this.setSelection(projectId);
  }

  showIssues(): void {
    this.onProjectChange(null);
    this.send({ type: "show-issues" });
  }

  setSelection(projectId: string | null): void {
    this.onProjectChange(projectId);
    this.send({ type: "show-project", projectId });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
    this.unsubscribeAgent();
  }

  private flags(initialProjectId: string | null): ProjectFlags {
    return {
      snapshot: this.snapshot(),
      projectMeta: this.projectMeta(),
      initialProjectId,
      isMac: /Mac|iPhone|iPad/.test(navigator.platform),
    };
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private projectMeta(): ElmProjectMetaDto[] {
    const snapshot = this.services.repository.index.getSnapshot();
    const breadcrumbs = projectBreadcrumbs(snapshot.projects);
    const descendantCounts = activeDescendantCounts(snapshot.projects);
    const supportCounts = this.services.repository.supportFileCounts();
    return snapshot.projects.map((project) => {
      const image = resolveVaultImage(
        this.services.app,
        project.image ?? this.services.getSettings().defaultProjectImage,
        project.file.path,
      );
      return {
        id: project.id,
        breadcrumb: breadcrumbs.get(project.id) ?? project.title,
        activeSubprojects: descendantCounts.get(project.id) ?? 0,
        supportFiles: supportCounts.get(project.id) ?? 0,
        imageUrl: image ? this.services.app.vault.getResourcePath(image) : "",
        actionIssue: projectActionIssue(project, snapshot.projects, snapshot.actions),
        blockers: activeProjectBlockers(project, snapshot.projectsById).map((blocker) => blocker.title),
      };
    });
  }

  private sendSnapshot(): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    // Metadata includes vault resources that are deliberately not part of the shared snapshot.
    this.send({ type: "project-meta", projectMeta: this.projectMeta() });
  }

  private sendAgent(): void {
    const agent = this.services.agent;
    this.send({
      type: "agent",
      agent: {
        available: agent.available(),
        runs: agent.views().map((run) => ({
          id: run.id,
          projectId: run.projectId,
          createdAt: localDateTime(run.createdAt),
          status: run.status,
          statusText: run.statusText,
          costUsd: run.costUsd,
          budgetUsd: run.budgetUsd,
          runtime: run.runtime,
          harness: run.harness ?? "",
          model: run.model,
          offline: run.offline,
          wholeVault: run.wholeVault,
          reportPath: run.reportPath,
          canUpdate: run.canUpdate,
          questions: run.status === "waiting" ? run.openQuestions : [],
          activity: (run.activity ?? []).map((entry) => ({ ...entry, at: localTimeOfDay(entry.at) })),
          repository: run.repository ?? "",
          branch: run.branch ?? "",
          pullRequestUrl: run.pullRequestUrl ?? "",
          previewUrl: run.previewUrl ?? "",
        })),
        costs: [...agent.costs()].map(([projectId, cost]) => ({ projectId, ...cost })),
      },
    });
  }

  private send(event: ElmProjectsEvent): void {
    if (!this.closed) this.app.ports.projectsFromHost.send(event);
  }

  private async execute(command: ElmProjectsCommand): Promise<unknown> {
    switch (command.type) {
      case "create-action":
        this.services.createAction(command.projectId);
        return;
      case "create-project":
        this.services.createProject(false, command.parentProjectId, command.status);
        return;
      case "set-project-selection":
        this.onProjectChange(command.projectId ?? null);
        return;
      case "edit-action":
        this.services.editAction(command.actionId, true);
        return;
      case "set-action-status":
        await this.services.repository.setActionStatus(command.actionId, command.status);
        return;
      case "trash-action": {
        const action = this.services.repository.index.getSnapshot().actionsById.get(command.actionId);
        if (!action) throw new Error("This Action no longer exists.");
        await trashWithUndo(this.services.app, action.file, `Deleted “${action.title}”.`,
          () => this.services.repository.trashAction(action.id));
        return;
      }
      case "edit-project":
        this.services.editProject(command.projectId);
        return;
      case "open-someday-review":
        this.services.openSomedayReview();
        return;
      case "open-pomodoro":
        this.services.openPomodoro(command.projectId);
        return;
      case "set-project-status":
        return setProjectStatus(this.services, command.projectId, command.status);
      case "set-project-area":
        if (this.project(command.projectId).parentProjectId) throw new Error("Only top-level Projects have an area.");
        return this.services.repository.updateProject(command.projectId, { area: command.area.trim() });
      case "move-subproject":
        return moveProject(this.services, command.projectId, command.status, command.beforeId);
      case "trash-project":
        await confirmDeleteProject(this.services, command.projectId);
        return;
      case "trash-projects":
        return confirmDeleteProjects(this.services, command.projectIds);
      case "batch-project-tags":
        new ElmModal(this.services, { kind: "batch-tags", projectIds: command.projectIds }).open();
        return;
      case "batch-project-parent":
        new ElmModal(this.services, { kind: "batch-parent", projectIds: command.projectIds }).open();
        return;
      case "project-dependencies":
        new ElmModal(this.services, { kind: "dependencies", projectId: this.project(command.projectId).id }).open();
        return;
      case "import-actions":
        this.services.importActions(command.projectId);
        return;
      case "import-subprojects":
        this.services.importSubprojects(command.projectId);
        return;
      case "open-file":
      case "create-support-note":
      case "create-support-folder":
      case "read-support-note":
      case "update-support-note":
      case "link-project-file":
      case "unlink-project-file":
      case "add-project-link":
      case "remove-project-link":
        return executeSupportCommand(this.services, command);
      case "load-project-detail": {
        const detail = await projectDetail(this.services, this.project(command.projectId));
        this.send({ type: "project-detail", detail });
        return;
      }
      case "set-desired-outcome":
        await this.services.repository.setDesiredOutcome(command.projectId, command.body.trim());
        return;
      case "add-diary-entry":
        return this.services.repository.addProjectDiaryEntry(command.projectId, command.body.trim());
      case "open-link":
        openWebLink(command.url);
        return;
      case "open-note-link":
        return this.services.app.workspace.openLinkText(command.link, command.sourcePath, false);
      case "save-project-preferences":
        await this.services.saveSettings({
          ...this.services.getSettings(),
          projectBoardColumns: command.columns,
          showProjectBoardImages: command.showImages,
          projectBoardColumnsBy: command.columnsBy,
          projectBoardSections: command.sections,
        }, false);
        return;
      case "show-menu":
        this.showMenu(command.x, command.y, command.entries);
        return;
      case "delegate-project":
        return this.services.delegateProject(command.projectId);
      case "answer-agent-question":
        return this.services.agent.answer(command.runId, command.questionId, command.answer);
      case "stop-agent-run":
        return this.services.agent.stop(command.runId);
      case "rerun-agent-run":
        return this.services.rerunAgentRun(command.runId);
      case "plan-project":
        return this.services.planProject(command.projectId);
      case "update-code-run": {
        const run = this.services.agent.views().find((candidate) => candidate.id === command.runId);
        if (!run) throw new Error("This run no longer exists.");
        await this.services.agent.updateCode(run.projectId);
        return;
      }
      case "delete-agent-run":
        return this.services.deleteAgentRun(command.runId);
    }
    return assertNever(command);
  }

  private project(id: string): Project {
    const project = this.services.repository.index.getSnapshot().projectsById.get(id);
    if (!project) throw new Error("This Project no longer exists.");
    return project;
  }

  private showMenu(x: number, y: number, entries: ElmProjectsMenuEntry[]): void {
    const menu = new Menu();
    for (const entry of entries) {
      if (entry.separator) menu.addSeparator();
      else if (entry.label && entry.command) menu.addItem((item) => item.setTitle(entry.label!).onClick(() => {
        void this.execute(entry.command!).catch((error: unknown) => {
          new Notice(error instanceof Error ? error.message : "The Project operation failed.");
        });
      }));
    }
    menu.showAtPosition({ x, y });
  }
}

/** An ISO timestamp as a date and time in this device's time zone, or as given when it doesn't parse. */
function localDateTime(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function localTimeOfDay(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "";
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
}
