// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { projectBreadcrumb } from "../domain/project-hierarchy";
import type { PomodoroService } from "../pomodoro/pomodoro-service";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { createUlid } from "../utils/ulid";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import {
  elmPomodoro,
  elmSnapshot,
  parsePomodoroCommand,
  type ElmPomodoroCommand,
  type ElmPomodoroEvent,
} from "./protocol";

interface ElmApp {
  ports: {
    pomodoroToHost: ElmOutgoingPort;
    pomodoroFromHost: { send(value: ElmPomodoroEvent): void };
  };
}

/** Hosts the Pomodoro view. The session itself lives in `PomodoroService`. */
export class ElmPomodoroHost {
  private readonly app: ElmApp;
  private readonly unsubscribeIndex: () => void;
  private readonly unsubscribePomodoro: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(
    node: HTMLElement,
    private readonly services: GtdServices,
    private readonly pomodoro: PomodoroService,
    initialProjectId: string | null,
  ) {
    const module = Elm.Pomodoro;
    if (!module) throw new Error("The Elm Pomodoro module was not compiled.");
    this.app = module.init({
      node,
      flags: { snapshot: this.snapshot(), pomodoro: this.state(), initialProjectId, nowMs: Date.now() },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.pomodoroToHost,
      parse: parsePomodoroCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      failureMessage: "The Pomodoro operation failed.",
    });
    this.unsubscribeIndex = services.repository.index.subscribe(() => this.send({ type: "snapshot", snapshot: this.snapshot() }));
    this.unsubscribePomodoro = pomodoro.subscribe(() => this.send({ type: "pomodoro", pomodoro: this.state() }));
  }

  refresh(): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    this.send({ type: "pomodoro", pomodoro: this.state() });
  }

  selectProject(projectId: string): void {
    this.send({ type: "select-project", projectId });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribeIndex();
    this.unsubscribePomodoro();
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private state() {
    return elmPomodoro(this.pomodoro.getStore(), this.services.getSettings().pomodoro.focusMinutes);
  }

  private send(event: ElmPomodoroEvent): void {
    if (!this.closed) this.app.ports.pomodoroFromHost.send(event);
  }

  private async execute(command: ElmPomodoroCommand): Promise<unknown> {
    switch (command.type) {
      case "start-pomodoro": {
        const snapshot = this.services.repository.index.getSnapshot();
        const project = snapshot.projectsById.get(command.projectId);
        if (!project) throw new Error("This Project no longer exists.");
        return this.pomodoro.begin({
          id: createUlid(),
          projectId: project.id,
          projectTitle: project.title,
          projectPath: projectBreadcrumb(project, snapshot.projectsById),
          intention: command.intention,
          focusActionIds: command.focusActionIds,
          plannedMinutes: command.minutes,
        });
      }
      case "pause-pomodoro":
        return this.pomodoro.pause();
      case "resume-pomodoro":
        return this.pomodoro.resume();
      case "finish-pomodoro":
        return this.pomodoro.finish({ outcome: command.outcome, reflection: command.reflection });
      case "discard-pomodoro":
        return this.pomodoro.discard();
      case "complete-pomodoro-action":
        await this.services.repository.setActionStatus(command.actionId, "done");
        return this.pomodoro.recordAction(command.actionId);
      case "show-project":
        this.services.showProjectDetail(command.projectId);
        return;
    }
    return assertNever(command);
  }
}
