import { Menu, Notice } from "obsidian";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { actionSchedule } from "../domain/schedule";
import type { GtdSettings } from "../domain/types";
import type { GtdServices } from "../ui/services";
import { ElmModal } from "./elm-modals";
import { localDate } from "../utils/date";
import {
  elmSnapshot,
  type ElmHostCommand,
  type ElmHostEvent,
  type ElmMenuEntry,
  parseElmCommand,
} from "./protocol";

interface ElmApp {
  ports: {
    toHost: { subscribe(listener: (value: unknown) => void): void };
    fromHost: { send(value: ElmHostEvent): void };
  };
}

export class ElmActionBoardHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private closed = false;

  constructor(node: HTMLElement, private readonly services: GtdServices) {
    const module = Elm.ActionBoard;
    if (!module) throw new Error("The Elm ActionBoard module was not compiled.");
    this.app = module.init({ node, flags: this.snapshot() }) as ElmApp;
    this.app.ports.toHost.subscribe((value) => void this.receive(value));
    this.unsubscribe = services.repository.index.subscribe(() => this.sendSnapshot());
  }

  refresh(): void {
    this.sendSnapshot();
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribe();
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private sendSnapshot(): void {
    if (!this.closed) this.app.ports.fromHost.send({ type: "snapshot", snapshot: this.snapshot() });
  }

  private async receive(value: unknown): Promise<void> {
    const envelope = parseElmCommand(value);
    if (!envelope) {
      new Notice("Dragonglass ignored an invalid Elm command.");
      return;
    }
    try {
      const result = await this.execute(envelope.command);
      this.reply({
        type: "command-result",
        requestId: envelope.requestId,
        ok: true,
        ...(result === undefined ? {} : { value: result }),
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "The GTD operation failed.";
      this.reply({ type: "command-result", requestId: envelope.requestId, ok: false, error: message });
      new Notice(message);
    }
  }

  private reply(event: ElmHostEvent): void {
    if (!this.closed) this.app.ports.fromHost.send(event);
  }

  private async execute(command: ElmHostCommand): Promise<unknown> {
    switch (command.type) {
      case "create-action":
        this.services.createAction(command.projectId);
        return;
      case "quick-capture":
        this.services.quickCapture();
        return;
      case "open-inbox":
        this.services.openInbox();
        return;
      case "show-project":
        this.services.showProjectDetail(command.projectId);
        return;
      case "edit-action":
        this.services.editAction(command.actionId);
        return;
      case "set-action-status": {
        const action = this.services.repository.index.getSnapshot().actionsById.get(command.actionId);
        if (!action) throw new Error("This Action is missing or has a duplicate ID.");
        if (command.status === "scheduled" && !actionSchedule(action.scheduledStart, action.durationMinutes)) {
          this.services.scheduleAction(command.actionId);
          return;
        }
        await this.services.repository.setActionStatus(command.actionId, command.status);
        return;
      }
      case "update-action":
        await this.services.repository.updateAction(command.actionId, {
          ...(command.projectId !== undefined ? { projectId: command.projectId } : {}),
          ...(command.context !== undefined ? { context: command.context } : {}),
        });
        return;
      case "trash-action": {
        const action = this.services.repository.index.getSnapshot().actionsById.get(command.actionId);
        if (!action) throw new Error("This Action is missing or has a duplicate ID.");
        if (!window.confirm(`Delete “${action.title}”?\n\nThis moves the Action file to Obsidian's trash.`)) return;
        await this.services.repository.trashAction(command.actionId);
        new Notice(`Deleted “${action.title}”.`);
        return;
      }
      case "save-settings":
        await this.services.saveSettings(command.settings as GtdSettings);
        return;
      case "prompt":
        return new Promise<string>((resolve) => {
          new ElmModal(
            this.services,
            { kind: "prompt", title: command.title, placeholder: command.placeholder },
            { onPrompt: resolve },
          ).open();
        });
      case "show-menu":
        this.showMenu(command.x, command.y, command.entries);
        return;
      default:
        throw new Error(`Unsupported Action Board command '${command.type}'.`);
    }
  }

  private showMenu(x: number, y: number, entries: ElmMenuEntry[]): void {
    const menu = new Menu();
    for (const entry of entries) {
      if (entry.separator) {
        menu.addSeparator();
      } else if (entry.label && entry.command) {
        menu.addItem((item) => item.setTitle(entry.label!).onClick(() => {
          void this.execute(entry.command!).catch((error: unknown) => {
            new Notice(error instanceof Error ? error.message : "The GTD operation failed.");
          });
        }));
      }
    }
    menu.showAtPosition({ x, y });
  }
}
