// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { moveProject, setProjectStatus } from "../ui/project-moves";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import {
  elmSnapshot,
  parseSomedayReviewCommand,
  type ElmSomedayReviewCommand,
  type ElmSomedayReviewEvent,
} from "./protocol";

interface ElmApp {
  ports: {
    somedayToHost: ElmOutgoingPort;
    somedayFromHost: { send(value: ElmSomedayReviewEvent): void };
  };
}

/** Hosts the Someday/Maybe Review, where each parked idea gets a decision. */
export class ElmSomedayReviewHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(node: HTMLElement, private readonly services: GtdServices) {
    const module = Elm.SomedayReview;
    if (!module) throw new Error("The Elm SomedayReview module was not compiled.");
    this.app = module.init({ node, flags: { snapshot: this.snapshot() } }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.somedayToHost,
      parse: parseSomedayReviewCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      failureMessage: "The Someday/Maybe Review operation failed.",
    });
    this.unsubscribe = services.repository.index.subscribe(() => this.refresh());
  }

  refresh(): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private send(event: ElmSomedayReviewEvent): void {
    if (!this.closed) this.app.ports.somedayFromHost.send(event);
  }

  private async execute(command: ElmSomedayReviewCommand): Promise<unknown> {
    switch (command.type) {
      case "set-project-status":
        return setProjectStatus(this.services, command.projectId, command.status);
      case "move-subproject":
        return moveProject(this.services, command.projectId, command.status, command.beforeId);
      case "review-someday-project":
        // Keeping an idea is a decision too; the date lets it wake itself up later.
        return this.services.repository.updateProject(command.projectId, { activateAt: command.activateAt, reviewed: localDate() });
      case "show-project":
        this.services.showProjectDetail(command.projectId);
        return;
    }
    return assertNever(command);
  }
}
