import { Menu, Notice, TFile } from "obsidian";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { activeDescendantCounts, projectBreadcrumbs } from "../domain/project-hierarchy";
import { activeProjectBlockers, projectActionIssue, projectPlacementsAfterMove } from "../domain/project-board";
import type { Project } from "../domain/types";
import { confirmDeleteProject, confirmDeleteProjects } from "../ui/delete-project";
import { isVaultImage, resolveVaultImage } from "../ui/image-input";
import { ElmModal } from "./elm-modals";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import {
  elmSnapshot,
  parseElmCommand,
  type ElmHostCommand,
  type ElmHostEvent,
  type ElmMenuEntry,
  type ElmProjectDetailDto,
  type ElmProjectMetaDto,
} from "./protocol";
import { registerObsidianMarkdown } from "./obsidian-markdown";

interface ElmApp {
  ports: {
    projectsToHost: { subscribe(listener: (value: unknown) => void): void };
    projectsFromHost: { send(value: ElmHostEvent): void };
  };
}

interface ProjectFlags {
  snapshot: ReturnType<typeof elmSnapshot>;
  projectMeta: ElmProjectMetaDto[];
  initialProjectId: string | null;
  isMac: boolean;
}

export class ElmProjectsHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private closed = false;

  constructor(
    node: HTMLElement,
    private readonly services: GtdServices,
    initialProjectId: string | null,
    private readonly onProjectChange: (projectId: string | null) => void,
  ) {
    registerObsidianMarkdown(services.app);
    const module = Elm.Projects;
    if (!module) throw new Error("The Elm Projects module was not compiled.");
    this.app = module.init({ node, flags: this.flags(initialProjectId) }) as ElmApp;
    this.app.ports.projectsToHost.subscribe((value) => void this.receive(value));
    this.unsubscribe = services.repository.index.subscribe(() => this.sendSnapshot());
  }

  refresh(): void {
    this.sendSnapshot();
  }

  showProject(projectId: string): void {
    this.setSelection(projectId);
  }

  setSelection(projectId: string | null): void {
    this.onProjectChange(projectId);
    this.send({ type: "show-project", projectId });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribe();
  }

  private flags(initialProjectId: string | null): ProjectFlags {
    return {
      snapshot: this.snapshot(),
      projectMeta: this.projectMeta(),
      initialProjectId,
      isMac: /Mac|iPhone|iPad/.test(navigator.platform),
    };
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private projectMeta(): ElmProjectMetaDto[] {
    const snapshot = this.services.repository.index.getSnapshot();
    const breadcrumbs = projectBreadcrumbs(snapshot.projects);
    const descendantCounts = activeDescendantCounts(snapshot.projects);
    const supportCounts = this.services.repository.supportFileCounts();
    const actionsByProject = new Map<string, typeof snapshot.actions>();
    for (const action of snapshot.actions) {
      if (!action.projectId) continue;
      actionsByProject.set(action.projectId, [...(actionsByProject.get(action.projectId) ?? []), action]);
    }
    return snapshot.projects.map((project) => {
      const image = resolveVaultImage(
        this.services.app,
        project.image ?? this.services.getSettings().defaultProjectImage,
        project.file.path,
      );
      return {
        id: project.id,
        breadcrumb: breadcrumbs.get(project.id) ?? project.title,
        activeSubprojects: descendantCounts.get(project.id) ?? 0,
        supportFiles: supportCounts.get(project.id) ?? 0,
        imageUrl: image ? this.services.app.vault.getResourcePath(image) : "",
        actionIssue: projectActionIssue(project, actionsByProject.get(project.id) ?? []),
        blockers: activeProjectBlockers(project, snapshot.projectsById).map((blocker) => blocker.title),
      };
    });
  }

  private sendSnapshot(): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    // Metadata includes vault resources that are deliberately not part of the shared snapshot.
    this.send({ type: "project-meta", projectMeta: this.projectMeta() });
  }

  private send(event: ElmHostEvent): void {
    if (!this.closed) this.app.ports.projectsFromHost.send(event);
  }

  private async receive(value: unknown): Promise<void> {
    const envelope = parseElmCommand(value);
    if (!envelope) return void new Notice("Dragonglass ignored an invalid Elm command.");
    try {
      const result = await this.execute(envelope.command);
      this.send({
        type: "command-result",
        requestId: envelope.requestId,
        ok: true,
        ...(result === undefined ? {} : { value: result }),
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "The Project operation failed.";
      this.send({ type: "command-result", requestId: envelope.requestId, ok: false, error: message });
      new Notice(message);
    }
  }

  private async execute(command: ElmHostCommand): Promise<unknown> {
    switch (command.type) {
      case "create-action":
        this.services.createAction(command.projectId);
        return;
      case "create-project":
        this.services.createProject(false, command.parentProjectId);
        return;
      case "set-project-selection":
        this.onProjectChange(command.projectId ?? null);
        return;
      case "edit-action":
        this.services.editAction(command.actionId, true);
        return;
      case "set-action-status":
        await this.services.repository.setActionStatus(command.actionId, command.status);
        return;
      case "trash-action": {
        const action = this.services.repository.index.getSnapshot().actionsById.get(command.actionId);
        if (!action) throw new Error("This Action no longer exists.");
        if (!window.confirm(`Delete “${action.title}”?\n\nThis moves the Action file to Obsidian's trash.`)) return;
        await this.services.repository.trashAction(command.actionId);
        return;
      }
      case "edit-project":
        this.services.editProject(command.projectId);
        return;
      case "set-project-status":
        await this.services.repository.setProjectStatus(command.projectId, command.status);
        return;
      case "move-subproject": {
        const snapshot = this.services.repository.index.getSnapshot();
        const moving = snapshot.projectsById.get(command.projectId);
        if (!moving?.parentProjectId) throw new Error("This sub-project no longer exists.");
        const siblings = snapshot.projects.filter((project) => project.parentProjectId === moving.parentProjectId);
        const placements = projectPlacementsAfterMove(siblings, command.projectId, command.status, command.beforeId);
        await Promise.all([...placements].map(([id, placement]) => this.services.repository.updateProject(id, placement)));
        return;
      }
      case "trash-project":
        await confirmDeleteProject(this.services, command.projectId);
        return;
      case "trash-projects":
        return confirmDeleteProjects(this.services, command.projectIds);
      case "batch-project-tags":
        new ElmModal(this.services, { kind: "batch-tags", projectIds: command.projectIds }).open();
        return;
      case "batch-project-parent":
        new ElmModal(this.services, { kind: "batch-parent", projectIds: command.projectIds }).open();
        return;
      case "project-dependencies":
        new ElmModal(this.services, { kind: "dependencies", projectId: this.project(command.projectId).id }).open();
        return;
      case "import-actions":
        this.services.importActions(command.projectId);
        return;
      case "import-subprojects":
        this.services.importSubprojects(command.projectId);
        return;
      case "load-project-detail": {
        const detail = await this.projectDetail(command.projectId);
        this.send({ type: "project-detail", detail });
        return;
      }
      case "set-desired-outcome":
        await this.services.repository.setDesiredOutcome(command.projectId, command.body.trim());
        return;
      case "add-diary-entry":
        return this.services.repository.addProjectDiaryEntry(command.projectId, command.body.trim());
      case "create-support-note":
        return (await this.services.repository.createProjectSupportNote(command.projectId, command.title)).path;
      case "create-support-folder":
        return this.services.repository.createProjectSupportFolder(command.projectId, command.path);
      case "read-support-note":
        return this.services.repository.readProjectSupportNote(command.projectId, command.path);
      case "update-support-note":
        await this.services.repository.updateProjectSupportNote(command.projectId, command.path, command.body);
        return;
      case "save-project-preferences":
        await this.services.saveSettings({
          ...this.services.getSettings(),
          projectBoardColumns: command.columns,
          showProjectBoardImages: command.showImages,
        }, false);
        return;
      case "open-file": {
        const file = this.services.app.vault.getAbstractFileByPath(command.path);
        if (!(file instanceof TFile)) throw new Error(`File '${command.path}' no longer exists.`);
        await this.services.openFile(file);
        return;
      }
      case "save-settings":
        await this.services.saveSettings(command.settings, false);
        return;
      case "show-menu":
        this.showMenu(command.x, command.y, command.entries);
        return;
      default:
        throw new Error(`Unsupported Projects command '${command.type}'.`);
    }
  }

  private project(id: string): Project {
    const project = this.services.repository.index.getSnapshot().projectsById.get(id);
    if (!project) throw new Error("This Project no longer exists.");
    return project;
  }

  private async projectDetail(projectId: string): Promise<ElmProjectDetailDto> {
    const project = this.project(projectId);
    const [desiredOutcome, diary] = await Promise.all([
      this.services.repository.readDesiredOutcome(project),
      this.services.repository.readProjectDiary(project),
    ]);
    const supportFiles = this.services.repository.supportFiles(project)
      .sort((left, right) => left.path.localeCompare(right.path))
      .map((file) => {
        const type = this.services.app.metadataCache.getFileCache(file)?.frontmatter?.type;
        const note = file.extension === "md" && type !== "gtd-action" && type !== "gtd-project" && type !== "gtd-inbox-item";
        const kind = note ? "note" as const : isVaultImage(file) ? "image" as const : "attachment" as const;
        return {
          path: file.path,
          name: file.name,
          basename: file.basename,
          extension: file.extension,
          label: project.supportPath && file.path.startsWith(`${project.supportPath}/`)
            ? file.path.slice(project.supportPath.length + 1)
            : file.name,
          kind,
          resourceUrl: kind === "image" ? this.services.app.vault.getResourcePath(file) : "",
        };
      });
    return {
      projectId,
      desiredOutcome,
      diary: diary.map((entry) => ({ timestamp: entry.timestamp ?? "", text: entry.text })),
      supportFiles,
      supportFolders: this.services.repository.supportFolders(project).map((path) => ({
        path,
        label: project.supportPath && path.startsWith(`${project.supportPath}/`)
          ? path.slice(project.supportPath.length + 1)
          : path,
      })),
    };
  }

  private showMenu(x: number, y: number, entries: ElmMenuEntry[]): void {
    const menu = new Menu();
    for (const entry of entries) {
      if (entry.separator) menu.addSeparator();
      else if (entry.label && entry.command) menu.addItem((item) => item.setTitle(entry.label!).onClick(() => {
        void this.execute(entry.command!).catch((error: unknown) => {
          new Notice(error instanceof Error ? error.message : "The Project operation failed.");
        });
      }));
    }
    menu.showAtPosition({ x, y });
  }
}
