import { Notice, TFile } from "obsidian";
import { trashWithUndo } from "../ui/undo";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { reviewWeekStart } from "../domain/weekly-review";
import { projectReviewHealth, projectReviewQueue } from "../domain/project-review";
import type { Project } from "../domain/types";
import { confirmDeleteProject } from "../ui/delete-project";
import { setProjectStatus } from "../ui/project-moves";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import { elmSnapshot, parseProjectReviewCommand, type ElmProjectReviewCommand, type ElmProjectReviewEvent } from "./protocol";

interface ElmApp {
  ports: {
    reviewToHost: ElmOutgoingPort;
    reviewFromHost: { send(value: ElmProjectReviewEvent): void };
  };
}

export class ElmProjectReviewHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;
  /** The review roots this session walks through, fixed when the review opens. */
  private queue: string[];
  /**
   * Whether the queue was taken from a read vault. A review left open is restored
   * when Obsidian starts, before the index has read anything, and an empty queue
   * would otherwise stand as "complete" for the whole session.
   */
  private queueFromVault: boolean;

  /** `continueToSomeday` puts the Someday/Maybe Review in this view's place once the review is done. */
  constructor(node: HTMLElement, private readonly services: GtdServices, private readonly continueToSomeday: () => void) {
    const module = Elm.ProjectReview;
    if (!module) throw new Error("The Elm ProjectReview module was not compiled.");
    this.queue = projectReviewQueue(services.repository.index.getSnapshot(), this.weekStart());
    this.queueFromVault = services.repository.index.getSnapshot().revision > 0;
    this.app = module.init({
      node,
      flags: {
        snapshot: this.snapshot(),
        queue: this.queue,
        health: this.health(),
        supportCounts: [...services.repository.supportFileCounts()].map(([projectId, count]) => ({ projectId, count })),
      },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.reviewToHost,
      parse: parseProjectReviewCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      failureMessage: "The Project review operation failed.",
    });
    this.unsubscribe = services.repository.index.subscribe(() => this.refresh());
  }

  refresh(): void {
    const indexed = this.services.repository.index.getSnapshot();
    if (!this.queueFromVault && indexed.revision > 0) {
      this.queueFromVault = true;
      this.queue = projectReviewQueue(indexed, this.weekStart());
      this.send({ type: "review-queue", queue: this.queue });
    }
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    this.send({ type: "review-health", health: this.health() });
    this.send({
      type: "support-counts",
      counts: [...this.services.repository.supportFileCounts()].map(([projectId, count]) => ({ projectId, count })),
    });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  /** Trees reviewed since this week's review day count as done, so a review can span days. */
  private weekStart(): string {
    return reviewWeekStart(localDate(), this.services.getSettings().weeklyReviewDay);
  }

  private health() {
    const snapshot = this.services.repository.index.getSnapshot();
    return projectReviewHealth(snapshot.projects, snapshot.actions, this.queue);
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private send(event: ElmProjectReviewEvent): void {
    if (!this.closed) this.app.ports.reviewFromHost.send(event);
  }

  private async execute(command: ElmProjectReviewCommand): Promise<unknown> {
    switch (command.type) {
      case "load-review-project": {
        const project = this.project(command.projectId);
        const [desiredOutcome, diary] = await Promise.all([
          this.services.repository.readDesiredOutcome(project),
          this.services.repository.readProjectDiary(project),
        ]);
        this.send({
          type: "review-project-data",
          data: { projectId: project.id, desiredOutcome, diary: diary.map((entry) => ({ timestamp: entry.timestamp ?? "", text: entry.text })) },
        });
        return;
      }
      case "create-review-action":
        await this.services.repository.createClarifiedAction({
          title: command.title.trim(),
          status: "next",
          projectId: command.projectId,
          context: command.context.trim(),
        });
        new Notice("Next Action created from a captured Inbox Item.");
        return;
      case "add-diary-entry":
        return this.services.repository.addProjectDiaryEntry(command.projectId, command.body);
      case "complete-project-review":
        await this.services.repository.setDesiredOutcome(command.projectId, command.desiredOutcome);
        await this.services.repository.markProjectsReviewed(command.activeProjectIds);
        return;
      case "move-review-to-someday":
        await this.services.repository.setDesiredOutcome(command.projectId, command.desiredOutcome);
        await this.services.repository.updateProject(command.projectId, { status: "someday", reviewed: localDate() });
        await this.services.repository.markProjectsReviewed(command.activeProjectIds.filter((id) => id !== command.projectId));
        new Notice(`Moved “${this.project(command.projectId).title}” to Someday/Maybe.`);
        return;
      case "trash-project":
        return confirmDeleteProject(this.services, command.projectId);
      case "set-project-status":
        return setProjectStatus(this.services, command.projectId, command.status);
      case "open-someday-review":
        this.continueToSomeday();
        return;
      case "create-project":
        this.services.createProject(false, command.parentProjectId, command.status);
        return;
      case "open-file": {
        const file = this.services.app.vault.getAbstractFileByPath(command.path);
        if (!(file instanceof TFile)) throw new Error(`File '${command.path}' no longer exists.`);
        await this.services.openFile(file);
        return;
      }
      case "edit-action":
        this.services.editAction(command.actionId, true);
        return;
      case "set-action-status":
        await this.services.repository.setActionStatus(command.actionId, command.status);
        return;
      case "trash-action": {
        const action = this.services.repository.index.getSnapshot().actionsById.get(command.actionId);
        if (!action) throw new Error("This Action no longer exists.");
        await trashWithUndo(this.services.app, action.file, `Deleted “${action.title}”.`,
          () => this.services.repository.trashAction(action.id));
        return;
      }
    }
    return assertNever(command);
  }

  private project(id: string): Project {
    const project = this.services.repository.index.getSnapshot().projectsById.get(id);
    if (!project) throw new Error("This Project no longer exists.");
    return project;
  }
}
