// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { checklistItems, findRun } from "../domain/checklist";
import { projectBreadcrumb } from "../domain/project-hierarchy";
import type { ChecklistService } from "../checklists/checklist-service";
import type { PomodoroService } from "../pomodoro/pomodoro-service";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { openWebLink } from "../ui/open-link";
import { createUlid } from "../utils/ulid";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import {
  elmChecklistRun,
  elmPomodoro,
  elmSnapshot,
  parsePomodoroCommand,
  type ElmPomodoroChecklists,
  type ElmPomodoroCommand,
  type ElmPomodoroEvent,
} from "./protocol";

/** What a session can be spent on. */
export type PomodoroSubject = { kind: "project"; projectId: string } | { kind: "checklist"; path: string };

interface ElmApp {
  ports: {
    pomodoroToHost: ElmOutgoingPort;
    pomodoroFromHost: { send(value: ElmPomodoroEvent): void };
  };
}

/** Hosts the Pomodoro view. The session itself lives in `PomodoroService`. */
export class ElmPomodoroHost {
  private readonly app: ElmApp;
  private readonly unsubscribeIndex: () => void;
  private readonly unsubscribePomodoro: () => void;
  private readonly unsubscribeChecklists: () => void;
  private readonly unsubscribePort: () => void;
  /** Checklists as last read; the notes are read asynchronously, so the first state has none. */
  private checklistState: ElmPomodoroChecklists = { choices: [], run: null };
  private version = 0;
  private closed = false;

  constructor(
    node: HTMLElement,
    private readonly services: GtdServices,
    private readonly pomodoro: PomodoroService,
    private readonly checklists: ChecklistService,
    initial: PomodoroSubject | null,
  ) {
    const module = Elm.Pomodoro;
    if (!module) throw new Error("The Elm Pomodoro module was not compiled.");
    this.app = module.init({
      node,
      flags: {
        snapshot: this.snapshot(),
        pomodoro: this.state(),
        initialProjectId: initial?.kind === "project" ? initial.projectId : null,
        initialChecklistPath: initial?.kind === "checklist" ? initial.path : null,
        nowMs: Date.now(),
      },
    }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.pomodoroToHost,
      parse: parsePomodoroCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.send(event),
      surface: "Pomodoro",
      failureMessage: "The Pomodoro operation failed.",
    });
    this.unsubscribeIndex = services.repository.index.subscribe(() => this.send({ type: "snapshot", snapshot: this.snapshot() }), "Pomodoro");
    this.unsubscribePomodoro = pomodoro.subscribe(() => {
      // The clock updates at once; the checklist run follows once its note is read.
      this.send({ type: "pomodoro", pomodoro: this.state() });
      void this.readChecklists();
    });
    this.unsubscribeChecklists = checklists.subscribe(() => void this.readChecklists());
    void this.readChecklists();
  }

  refresh(): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    void this.readChecklists();
  }

  select(subject: PomodoroSubject): void {
    this.send(subject.kind === "project"
      ? { type: "select-project", projectId: subject.projectId }
      : { type: "select-checklist", path: subject.path });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribeIndex();
    this.unsubscribePomodoro();
    this.unsubscribeChecklists();
  }

  /** Reads the checklists and the running session's run, then sends the whole state. */
  private async readChecklists(): Promise<void> {
    const version = ++this.version;
    const choices = [];
    for (const note of this.checklists.checklists()) {
      choices.push({ ...note, itemCount: checklistItems((await this.checklists.read(note.path)) ?? []).length });
    }
    const runId = this.pomodoro.getStore().active?.checklist?.runId;
    const store = this.checklists.getStore();
    const run = runId ? findRun(store, runId) : undefined;
    const state = { choices, run: run ? elmChecklistRun(run, await this.checklists.read(run.path), store) : null };
    if (version !== this.version) return;
    this.checklistState = state;
    this.send({ type: "pomodoro", pomodoro: this.state() });
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private state() {
    const settings = this.services.getSettings().pomodoro;
    return elmPomodoro(this.pomodoro.getStore(), settings.focusMinutes, new Date(), this.checklistState, {
      sound: settings.sound,
      folder: settings.soundFolder,
    });
  }

  private send(event: ElmPomodoroEvent): void {
    if (!this.closed) this.app.ports.pomodoroFromHost.send(event);
  }

  private async execute(command: ElmPomodoroCommand): Promise<unknown> {
    switch (command.type) {
      case "start-pomodoro": {
        const snapshot = this.services.repository.index.getSnapshot();
        const project = snapshot.projectsById.get(command.projectId);
        if (!project) throw new Error("This Project no longer exists.");
        return this.pomodoro.begin({
          id: createUlid(),
          projectId: project.id,
          projectTitle: project.title,
          projectPath: projectBreadcrumb(project, snapshot.projectsById),
          intention: command.intention,
          focusActionIds: command.focusActionIds,
          plannedMinutes: command.minutes,
        });
      }
      case "pause-pomodoro":
        return this.pomodoro.pause();
      case "resume-pomodoro":
        return this.pomodoro.resume();
      case "finish-pomodoro":
        return this.pomodoro.finish({ outcome: command.outcome, reflection: command.reflection });
      case "discard-pomodoro":
        return this.pomodoro.discard();
      case "set-pomodoro-sound": {
        const settings = this.services.getSettings();
        await this.services.saveSettings({ ...settings, pomodoro: { ...settings.pomodoro, sound: command.sound } }, false);
        this.pomodoro.soundChanged();
        this.send({ type: "pomodoro", pomodoro: this.state() });
        return;
      }
      case "start-checklist-pomodoro": {
        const run = await this.checklists.begin(command.path);
        return this.pomodoro.begin({
          id: createUlid(),
          projectId: "",
          projectTitle: run.title,
          projectPath: "",
          checklist: { runId: run.id, path: run.path },
          intention: command.intention,
          focusActionIds: [],
          plannedMinutes: command.minutes,
        });
      }
      case "mark-checklist-item":
        return this.checklists.mark(command.runId, command.key, command.state);
      case "open-checklist-run":
        this.services.openChecklists(command.runId);
        return;
      case "complete-pomodoro-action":
        await this.services.repository.setActionStatus(command.actionId, "done");
        return this.pomodoro.recordAction(command.actionId);
      case "show-project":
        this.services.showProjectDetail(command.projectId);
        return;
      case "open-link":
        openWebLink(command.url);
        return;
      case "open-note-link":
        return this.services.app.workspace.openLinkText(command.link, command.sourcePath, false);
    }
    return assertNever(command);
  }
}
