import { Menu, Notice, TFile } from "obsidian";
import { trashWithUndo } from "../ui/undo";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { actionSchedule } from "../domain/schedule";
import { actionRequiresContext } from "../domain/action-status";
import type { GtdServices } from "../ui/services";
import { ElmModal } from "./elm-modals";
import { localDate } from "../utils/date";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "./elm-host";
import {
  elmSnapshot,
  type ElmActionBoardCommand,
  type ElmActionBoardEvent,
  type ElmActionBoardMenuEntry,
  parseActionBoardCommand,
} from "./protocol";

interface ElmApp {
  ports: {
    toHost: ElmOutgoingPort;
    fromHost: { send(value: ElmActionBoardEvent): void };
  };
}

export class ElmActionBoardHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private readonly unsubscribePort: () => void;
  private closed = false;

  constructor(node: HTMLElement, private readonly services: GtdServices) {
    const module = Elm.ActionBoard;
    if (!module) throw new Error("The Elm ActionBoard module was not compiled.");
    this.app = module.init({ node, flags: this.snapshot() }) as ElmApp;
    this.unsubscribePort = subscribeElmCommands({
      port: this.app.ports.toHost,
      parse: parseActionBoardCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.reply(event),
      failureMessage: "The GTD operation failed.",
    });
    this.unsubscribe = services.repository.index.subscribe(() => this.sendSnapshot());
  }

  refresh(): void {
    this.sendSnapshot();
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribePort();
    this.unsubscribe();
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private sendSnapshot(): void {
    if (!this.closed) this.app.ports.fromHost.send({ type: "snapshot", snapshot: this.snapshot() });
  }

  private reply(event: ElmActionBoardEvent): void {
    if (!this.closed) this.app.ports.fromHost.send(event);
  }

  private async execute(command: ElmActionBoardCommand): Promise<unknown> {
    switch (command.type) {
      case "create-action":
        this.services.createAction(command.projectId);
        return;
      case "quick-capture":
        this.services.quickCapture();
        return;
      case "open-file": {
        const file = this.services.app.vault.getAbstractFileByPath(command.path);
        if (!(file instanceof TFile)) throw new Error(`File '${command.path}' no longer exists.`);
        await this.services.openFile(file);
        return;
      }
      case "open-inbox":
        this.services.openInbox();
        return;
      case "show-project":
        this.services.showProjectDetail(command.projectId);
        return;
      case "edit-action":
        this.services.editAction(command.actionId);
        return;
      case "set-action-status": {
        const action = this.services.repository.index.getSnapshot().actionsById.get(command.actionId);
        if (!action) throw new Error("This Action is missing or has a duplicate ID.");
        // Next and Calendar Actions need a context, which a Waiting Action gave up: ask for it.
        if (actionRequiresContext(command.status) && !action.context?.trim()) {
          this.services.editAction(command.actionId, false, command.status);
          return;
        }
        if (command.status === "scheduled" && !actionSchedule(action.scheduledStart, action.durationMinutes)) {
          this.services.scheduleAction(command.actionId);
          return;
        }
        await this.services.repository.setActionStatus(command.actionId, command.status);
        return;
      }
      case "set-action-priorities":
        await this.services.repository.setActionPriorities(command.actionIds);
        return;
      case "update-action":
        await this.services.repository.updateAction(command.actionId, {
          ...(command.projectId !== undefined ? { projectId: command.projectId } : {}),
          ...(command.context !== undefined ? { context: command.context } : {}),
        });
        return;
      case "trash-action": {
        const action = this.services.repository.index.getSnapshot().actionsById.get(command.actionId);
        if (!action) throw new Error("This Action is missing or has a duplicate ID.");
        await trashWithUndo(this.services.app, action.file, `Deleted “${action.title}”.`,
          () => this.services.repository.trashAction(action.id));
        return;
      }
      case "set-active-saved-view":
        await this.services.saveSettings({
          ...this.services.getSettings(),
          activeSavedViewId: command.savedViewId,
        });
        return;
      case "upsert-saved-view": {
        const settings = this.services.getSettings();
        const exists = settings.savedViews.some((view) => view.id === command.view.id);
        await this.services.saveSettings({
          ...settings,
          savedViews: exists
            ? settings.savedViews.map((view) => view.id === command.view.id ? command.view : view)
            : [...settings.savedViews, command.view],
          activeSavedViewId: command.activate ? command.view.id : settings.activeSavedViewId,
        });
        return;
      }
      case "delete-saved-view": {
        const settings = this.services.getSettings();
        await this.services.saveSettings({
          ...settings,
          savedViews: settings.savedViews.filter((view) => view.id !== command.savedViewId),
          activeSavedViewId: settings.activeSavedViewId === command.savedViewId ? null : settings.activeSavedViewId,
        });
        return;
      }
      case "prompt":
        return new Promise<string>((resolve) => {
          new ElmModal(
            this.services,
            { kind: "prompt", title: command.title, placeholder: command.placeholder },
            { onPrompt: resolve },
          ).open();
        });
      case "show-menu":
        this.showMenu(command.x, command.y, command.entries);
        return;
    }
    return assertNever(command);
  }

  private showMenu(x: number, y: number, entries: ElmActionBoardMenuEntry[]): void {
    const menu = new Menu();
    for (const entry of entries) {
      if (entry.separator) {
        menu.addSeparator();
      } else if (entry.label && entry.command) {
        menu.addItem((item) => item.setTitle(entry.label!).onClick(() => {
          void this.execute(entry.command!).catch((error: unknown) => {
            new Notice(error instanceof Error ? error.message : "The GTD operation failed.");
          });
        }));
      }
    }
    menu.showAtPosition({ x, y });
  }
}
