import { Notice, TFile } from "obsidian";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { projectReviewQueue } from "../domain/project-review";
import type { Project } from "../domain/types";
import { confirmDeleteProject } from "../ui/delete-project";
import type { GtdServices } from "../ui/services";
import { localDate } from "../utils/date";
import { elmSnapshot, parseElmCommand, type ElmHostCommand, type ElmHostEvent } from "./protocol";

interface ElmApp {
  ports: {
    reviewToHost: { subscribe(listener: (value: unknown) => void): void };
    reviewFromHost: { send(value: ElmHostEvent): void };
  };
}

export class ElmProjectReviewHost {
  private readonly app: ElmApp;
  private readonly unsubscribe: () => void;
  private closed = false;

  constructor(node: HTMLElement, private readonly services: GtdServices) {
    const module = Elm.ProjectReview;
    if (!module) throw new Error("The Elm ProjectReview module was not compiled.");
    const snapshot = services.repository.index.getSnapshot();
    this.app = module.init({
      node,
      flags: {
        snapshot: this.snapshot(),
        queue: projectReviewQueue(snapshot, localDate()),
        supportCounts: [...services.repository.supportFileCounts()].map(([projectId, count]) => ({ projectId, count })),
      },
    }) as ElmApp;
    this.app.ports.reviewToHost.subscribe((value) => void this.receive(value));
    this.unsubscribe = services.repository.index.subscribe(() => this.refresh());
  }

  refresh(): void {
    this.send({ type: "snapshot", snapshot: this.snapshot() });
    this.send({
      type: "command-result",
      requestId: "review-support-counts",
      ok: true,
      value: [...this.services.repository.supportFileCounts()].map(([projectId, count]) => ({ projectId, count })),
    });
  }

  destroy(): void {
    this.closed = true;
    this.unsubscribe();
  }

  private snapshot() {
    return elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate());
  }

  private send(event: ElmHostEvent): void {
    if (!this.closed) this.app.ports.reviewFromHost.send(event);
  }

  private async receive(value: unknown): Promise<void> {
    const envelope = parseElmCommand(value);
    if (!envelope) return void new Notice("Dragonglass ignored an invalid Elm command.");
    try {
      const result = await this.execute(envelope.command);
      this.send({ type: "command-result", requestId: envelope.requestId, ok: true, ...(result === undefined ? {} : { value: result }) });
    } catch (error) {
      const message = error instanceof Error ? error.message : "The Project review operation failed.";
      this.send({ type: "command-result", requestId: envelope.requestId, ok: false, error: message });
      new Notice(message);
    }
  }

  private async execute(command: ElmHostCommand): Promise<unknown> {
    switch (command.type) {
      case "load-review-project": {
        const project = this.project(command.projectId);
        const [desiredOutcome, diary] = await Promise.all([
          this.services.repository.readDesiredOutcome(project),
          this.services.repository.readProjectDiary(project),
        ]);
        this.send({
          type: "review-project-data",
          data: { projectId: project.id, desiredOutcome, diary: diary.map((entry) => ({ timestamp: entry.timestamp ?? "", text: entry.text })) },
        });
        return;
      }
      case "create-review-action":
        await this.services.repository.createClarifiedAction({
          title: command.title.trim(),
          status: "next",
          projectId: command.projectId,
          context: command.context.trim(),
          work: command.work,
        });
        new Notice("Next Action created from a captured Inbox Item.");
        return;
      case "add-diary-entry":
        return this.services.repository.addProjectDiaryEntry(command.projectId, command.body);
      case "complete-project-review":
        await this.services.repository.setDesiredOutcome(command.projectId, command.desiredOutcome);
        for (const id of command.activeProjectIds) await this.services.repository.markProjectReviewed(id);
        return;
      case "move-review-to-someday":
        await this.services.repository.setDesiredOutcome(command.projectId, command.desiredOutcome);
        await this.services.repository.updateProject(command.projectId, { status: "someday", reviewed: localDate() });
        for (const id of command.activeProjectIds) {
          if (id !== command.projectId) await this.services.repository.markProjectReviewed(id);
        }
        new Notice(`Moved “${this.project(command.projectId).title}” to Someday/Maybe.`);
        return;
      case "trash-project":
        return confirmDeleteProject(this.services, command.projectId);
      case "create-project":
        this.services.createProject(false, command.parentProjectId);
        return;
      case "open-file": {
        const file = this.services.app.vault.getAbstractFileByPath(command.path);
        if (!(file instanceof TFile)) throw new Error(`File '${command.path}' no longer exists.`);
        await this.services.openFile(file);
        return;
      }
      case "edit-action":
        this.services.editAction(command.actionId, true);
        return;
      case "set-action-status":
        await this.services.repository.setActionStatus(command.actionId, command.status);
        return;
      case "trash-action": {
        const action = this.services.repository.index.getSnapshot().actionsById.get(command.actionId);
        if (!action) throw new Error("This Action no longer exists.");
        if (!window.confirm(`Delete “${action.title}”?\n\nThis moves the Action file to Obsidian's trash.`)) return;
        await this.services.repository.trashAction(command.actionId);
        return;
      }
      default:
        throw new Error(`Unsupported Project Review command '${command.type}'.`);
    }
  }

  private project(id: string): Project {
    const project = this.services.repository.index.getSnapshot().projectsById.get(id);
    if (!project) throw new Error("This Project no longer exists.");
    return project;
  }
}
