import { Modal } from "obsidian";
// Generated by scripts/build-elm.mjs before TypeScript is checked or bundled.
// @ts-expect-error The generated module does not exist in a clean checkout.
import { Elm } from "../../.generated/elm-runtime.js";
import { assertNever, subscribeElmCommands, type ElmOutgoingPort } from "../adapter/elm-host";
import { elmSnapshot, parsePlanProjectCommand, type ElmCommandResultEvent, type ElmPlanProjectCommand } from "../adapter/protocol";
import { activeProjectBlockers } from "../domain/project-board";
import { planDiaryEntry, plannedSteps, type PlanItem } from "../domain/project-plan";
import { projectReviewMembers, projectsNeedingAction } from "../domain/project-review";
import { localDate } from "../utils/date";
import { MOD_ENTER_EVENT } from "./mod-enter";
import type { GtdServices } from "./services";

interface ElmApp {
  ports: {
    planToHost: ElmOutgoingPort;
    planFromHost: { send(value: ElmCommandResultEvent): void };
  };
}

/** How long to wait for the index to read what the plan just wrote, before answering anyway. */
const INDEX_WAIT_MS = 3_000;

/**
 * Plans a Project in one dialog (the Elm `PlanProject` program): purpose, desired outcome, ideas,
 * what each idea becomes, then the branches still without a Next Action. The dialog decides; this
 * host writes the plan into ordinary Dragonglass data (sections of the Project note, Actions,
 * Sub-projects, blockers, a Diary entry) and answers with the branches that still need a step.
 */
export async function planProject(services: GtdServices, projectId: string, onClose?: () => void): Promise<void> {
  const project = services.repository.index.getSnapshot().projectsById.get(projectId);
  if (!project) throw new Error("This Project no longer exists.");
  const [purpose, desiredOutcome] = await Promise.all([
    services.repository.readProjectPurpose(project),
    services.repository.readDesiredOutcome(project),
  ]);
  new PlanProjectModal(services, projectId, purpose, desiredOutcome, onClose).open();
}

class PlanProjectModal extends Modal {
  private app_: ElmApp | null = null;
  private unsubscribePort: (() => void) | null = null;

  constructor(
    private readonly services: GtdServices,
    private readonly projectId: string,
    private readonly purpose: string,
    private readonly desiredOutcome: string,
    /** E.g. the Project Review reloading the outcome the plan may have changed. */
    private readonly onClosed?: () => void,
  ) {
    super(services.app);
  }

  onOpen(): void {
    this.modalEl.addClass("dg-modal-shell", "dg-plan-shell");
    this.contentEl.addClass("dg-modal");
    const module = Elm.PlanProject;
    if (!module) throw new Error("The Elm PlanProject module was not compiled.");
    // A child node, so Elm never renders into contentEl itself (see CLAUDE.md, "Elm views that keep time").
    this.app_ = module.init({
      node: this.contentEl.createDiv(),
      flags: {
        snapshot: elmSnapshot(this.services.repository.index.getSnapshot(), this.services.getSettings(), localDate()),
        projectId: this.projectId,
        purpose: this.purpose,
        desiredOutcome: this.desiredOutcome,
      },
    }) as ElmApp;
    // ⌘+Enter moves to the next step. Obsidian's keymap takes the chord first, so the dialog's own scope
    // claims it and hands it to the focused field (`Ui.onModEnter`), as routeModEnter does for views.
    this.scope.register(["Mod"], "Enter", (evt) => {
      if (evt.target instanceof HTMLElement && this.contentEl.contains(evt.target)) {
        evt.target.dispatchEvent(new CustomEvent(MOD_ENTER_EVENT, { bubbles: true }));
      }
      return false;
    });
    this.contentEl.addEventListener("keydown", (evt) => {
      if (evt.key !== "Enter" || !(evt.ctrlKey || evt.metaKey) || evt.defaultPrevented) return;
      evt.preventDefault();
      evt.target?.dispatchEvent(new CustomEvent(MOD_ENTER_EVENT, { bubbles: true }));
    });
    this.unsubscribePort = subscribeElmCommands({
      port: this.app_.ports.planToHost,
      parse: parsePlanProjectCommand,
      execute: (command) => this.execute(command),
      reply: (event) => this.app_?.ports.planFromHost.send(event),
      surface: "Plan Project",
      failureMessage: "The plan could not be written.",
      notifyErrors: false,
    });
  }

  onClose(): void {
    this.unsubscribePort?.();
    this.unsubscribePort = null;
    this.app_ = null;
    this.onClosed?.();
  }

  private async execute(command: ElmPlanProjectCommand): Promise<unknown> {
    switch (command.type) {
      case "save-project-plan":
        return this.savePlan(command.purpose, command.desiredOutcome, command.items);
      case "add-plan-action": {
        const id = await this.services.repository.createAction({
          title: command.title,
          status: "next",
          projectId: command.projectId,
          context: command.context,
        });
        await this.indexed([id]);
        return { gaps: this.gaps() };
      }
      case "delegate-plan-project":
        this.close();
        await this.services.delegateProject(command.projectId);
        return;
      case "close-plan":
        this.close();
        return;
    }
    return assertNever(command);
  }

  /**
   * Writes the plan: Purpose and Desired outcome sections, Sub-projects (each after the one it waits
   * for), Someday sub-projects, Next Actions, and a Diary entry that keeps every decision, dropped
   * ideas included. Checked as a whole first, so a mistake writes nothing.
   */
  private async savePlan(purpose: string, desiredOutcome: string, items: readonly PlanItem[]): Promise<unknown> {
    const { repository } = this.services;
    const snapshot = repository.index.getSnapshot();
    const root = snapshot.projectsById.get(this.projectId);
    if (!root) throw new Error("This Project no longer exists.");
    const tree = new Set(projectReviewMembers(root, snapshot.projects).map((project) => project.id));
    const steps = plannedSteps(items, tree);

    await repository.setProjectPurpose(root.id, purpose);
    await repository.setDesiredOutcome(root.id, desiredOutcome);

    const created = new Map<number, string>();
    for (const planned of steps.subprojects) {
      const id = await repository.createProjectWithId({
        title: planned.title,
        status: planned.someday ? "someday" : "active",
        parentProjectId: root.id,
      });
      created.set(planned.index, id);
    }
    await this.indexed([...created.values()]);
    for (const planned of steps.subprojects) {
      const blocker = planned.afterIdea !== undefined ? created.get(planned.afterIdea) : planned.afterProjectId;
      if (blocker) await repository.updateProject(created.get(planned.index)!, { blockedByProjectIds: [blocker] });
    }
    const actionIds: string[] = [];
    for (const action of steps.actions) {
      actionIds.push(await repository.createAction({ title: action.title, status: "next", projectId: root.id, context: action.context }));
    }
    if (steps.subprojects.length || steps.actions.length || steps.dropped.length) {
      await repository.addProjectDiaryEntry(root.id, planDiaryEntry(steps));
    }
    await this.indexed(actionIds);
    return { gaps: this.gaps() };
  }

  /**
   * Active branches of the tree without a Next Action, as the review check finds them. A Sub-project
   * still waiting for another can't take a step yet, so it isn't listed.
   */
  private gaps(): Array<{ projectId: string; title: string }> {
    const snapshot = this.services.repository.index.getSnapshot();
    const root = snapshot.projectsById.get(this.projectId);
    if (!root) return [];
    return projectsNeedingAction(projectReviewMembers(root, snapshot.projects), snapshot.actions)
      .filter((project) => activeProjectBlockers(project, snapshot.projectsById).length === 0)
      .map((project) => ({ projectId: project.id, title: project.title }));
  }

  /** Waits until the index has read the given Projects and Actions, so the answer counts them. */
  private async indexed(ids: readonly string[]): Promise<void> {
    const deadline = Date.now() + INDEX_WAIT_MS;
    while (Date.now() < deadline) {
      const snapshot = this.services.repository.index.getSnapshot();
      if (ids.every((id) => snapshot.projectsById.has(id) || snapshot.actionsById.has(id))) return;
      await new Promise((resolve) => window.setTimeout(resolve, 50));
    }
  }
}
